import type { IncomingPacketConstructor } from '@nitrodevco/nitro-api';

import {
    AcceptFriendResultMessage,
    AccountPreferencesEventMessage,
    AccountSafetyLockStatusChangeMessage,
    AchievementEventMessage,
    AchievementsEventMessage,
    AchievementsScoreEventMessage,
    ActivityPointsMessage,
    ApproveNameMessage,
    AreaHideMessage,
    AuthenticationOKMessage,
    AvailabilityStatusMessage,
    AvatarEffectActivatedMessage,
    AvatarEffectAddedMessage,
    AvatarEffectExpiredMessage,
    AvatarEffectMessage,
    AvatarEffectSelectedMessage,
    AvatarEffectsMessage,
    BadgePointLimitsEventMessage,
    BadgeReceivedEventMessage,
    BadgesEventMessage,
    BonusRareInfoMessage,
    BotAddedToInventoryEventMessage,
    BotCommandConfigurationMessage,
    BotErrorMessage,
    BotForceOpenContextMenuMessage,
    BotInventoryEventMessage,
    BotRemovedFromInventoryEventMessage,
    BotSkillListUpdateMessage,
    BuildersClubPlacementWarningMessage,
    BuildersClubSubscriptionStatusMessage,
    BundleDiscountRulesetMessage,
    CameraPublishStatusMessage,
    CameraPurchaseOKMessage,
    CameraStorageUrlMessage,
    CampaignCalendarDataMessage,
    CampaignCalendarDoorOpenedMessage,
    CancelMysteryBoxWaitMessage,
    CanCreateRoomEventMessage,
    CanCreateRoomMessage,
    CantConnectMessage,
    CarryObjectMessage,
    CatalogIndexMessage,
    CatalogPageMessage,
    CatalogPageWithEarliestExpiryMessage,
    CatalogPublishedMessage,
    CategoriesWithVisitorCountMessage,
    CfhSanctionMessage,
    CfhTopicsInitMessage,
    ChangeEmailResultEventMessage,
    ChangeUserNameResultMessage,
    ChatMessage,
    CheckUserNameResultMessage,
    CloseConnectionMessage,
    ClubGiftInfoEventMessage,
    ClubGiftNotificationEventMessage,
    ClubGiftSelectedEventMessage,
    CollectableMintableItemTypesMessage,
    CollectibleMintableItemResultMessage,
    CollectibleMintingEnabledMessage,
    CollectibleMintTokenCountMessage,
    CollectibleMintTokenOffersMessage,
    CollectibleWalletAddressesMessage,
    CompetitionRoomsDataMessage,
    CompetitionStatusMessage,
    CompleteDiffieHandshakeMessage,
    ConfirmBreedingRequestEventMessage,
    ConfirmBreedingResultEventMessage,
    ConsoleMessageHistoryMessage,
    ConvertedRoomIdMessage,
    CreditBalanceEventMessage,
    CreditVaultStatusMessage,
    CustomStackingHeightUpdateMessage,
    CustomUserNotificationMessage,
    DanceMessage,
    DiceValueMessage,
    DoorbellMessage,
    ElementPointerMessage,
    EmailStatusResultEventMessage,
    EmeraldBalanceMessage,
    ExpressionMessage,
    ExtendedProfileChangedMessage,
    FavoriteMembershipUpdateMessage,
    FavouriteChangedMessage,
    FavouritesMessage,
    FigureSetIdsEventMessage,
    FigureUpdateEventMessage,
    FlatAccessDeniedMessage,
    FlatAccessibleMessage,
    FlatCreatedMessage,
    FloodControlMessage,
    FloorHeightMapMessage,
    FollowFriendFailedMessage,
    FriendListFragmentMessage,
    FriendListUpdateMessage,
    FriendNotificationMessage,
    FriendRequestsMessage,
    FurniListAddOrUpdateEventMessage,
    FurniListEventMessage,
    FurniListInvalidateEventMessage,
    FurniListRemoveEventMessage,
    FurniRentOrBuyoutOfferMessage,
    FurnitureAliasesMessage,
    GamePlayerValueMessage,
    GenericErrorMessage,
    GetGuestRoomResultMessage,
    GiftReceiverNotFoundEventMessage,
    GiftWrappingConfigurationEventMessage,
    GotMysteryBoxPrizeMessage,
    GoToBreedingNestFailureEventMessage,
    GuestRoomSearchResultMessage,
    GuildFurniContextMenuInfoMessage,
    HabboAchievementNotificationMessage,
    HabboActivityPointNotificationMessage,
    HabboBroadcastMessage,
    HabboClubExtendOfferMessage,
    HabboClubOffersMessage,
    HabboSearchResultMessage,
    HanditemConfigurationMessage,
    HeightMapMessage,
    HeightMapUpdateMessage,
    IncomeRewardClaimResponseMessage,
    IncomeRewardStatusMessage,
    InfoFeedEnableMessage,
    InfoHotelClosedMessage,
    InfoHotelClosingMessage,
    InitCameraMessage,
    InitDiffieHandshakeMessage,
    InstantMessageErrorMessage,
    InterstitialMessage,
    IsBadgeRequestFulfilledEventMessage,
    IsFirstLoginOfDayMessage,
    ItemAddMessage,
    ItemDataUpdateMessage,
    ItemRemoveMessage,
    ItemsMessage,
    ItemsStateUpdateMessage,
    ItemStateUpdateMessage,
    ItemUpdateMessage,
    LatencyPingResponseMessage,
    LimitedEditionSoldOutEventMessage,
    LimitedOfferAppearingNextMessage,
    LoginFailedHotelClosedMessage,
    MaintenanceStatusMessage,
    MessengerErrorMessage,
    MessengerInitMessage,
    MiniMailNewMessage,
    MiniMailUnreadCountMessage,
    MOTDNotificationEventMessage,
    MysteryBoxKeysMessage,
    NavigatorCollapsedCategoriesMessage,
    NavigatorLiftedRoomsMessage,
    NavigatorMetadataMessage,
    NavigatorSavedSearchesMessage,
    NavigatorSearchResultBlocksMessage,
    NavigatorSettingsMessage,
    NestBreedingSuccessEventMessage,
    NewConsoleMessageMessage,
    NewFriendRequestMessage,
    NewNavigatorPreferencesMessage,
    NftBonusItemClaimResultMessage,
    NftCollectionsMessage,
    NftCollectionsScoreMessage,
    NftRewardItemClaimResultMessage,
    NftTransferAssetsResultMessage,
    NftTransferFeeMessage,
    NoobnessLevelMessage,
    NotEnoughBalanceMessage,
    NotificationDialogMessage,
    ObjectAddMessage,
    ObjectDataUpdateMessage,
    ObjectRemoveConfirmMessage,
    ObjectRemoveMessage,
    ObjectRemoveMultipleMessage,
    ObjectsDataUpdateMessage,
    ObjectsMessage,
    ObjectUpdateMessage,
    OfferRewardDeliveredMessage,
    OfficialRoomsMessage,
    OneWayDoorStatusMessage,
    OpenConnectionMessage,
    OpenEventMessage,
    OpenPetPackageRequestedMessage,
    OpenPetPackageResultMessage,
    PetAddedToInventoryEventMessage,
    PetBreedingEventMessage,
    PetBreedingResultEventMessage,
    PetCommandsMessage,
    PetExperienceMessage,
    PetFigureUpdateMessage,
    PetInfoMessage,
    PetInventoryEventMessage,
    PetLevelNotificationEventMessage,
    PetLevelUpdateMessage,
    PetPlacingErrorMessage,
    PetReceivedMessage,
    PetRemovedFromInventoryEventMessage,
    PetRespectFailedMessage,
    PetStatusUpdateMessage,
    PingMessage,
    PopularRoomTagsResultMessage,
    PostItPlacedEventMessage,
    PresentOpenedMessage,
    ProductOfferEventMessage,
    PurchaseErrorMessage,
    PurchaseNotAllowedMessage,
    PurchaseOKMessage,
    RemainingMutePeriodMessage,
    RentableSpaceRentFailedMessage,
    RentableSpaceRentOkMessage,
    RentableSpaceStatusMessage,
    RequestSpamWallPostItMessage,
    RestoreClientMessage,
    RoomAdErrorEventMessage,
    RoomAdPurchaseInfoEventMessage,
    RoomChatSettingsMessage,
    RoomDimmerPresetsMessage,
    RoomEntryInfoMessage,
    RoomEntryTileMessage,
    RoomEventCancelMessage,
    RoomEventMessage,
    RoomFilterSettingsMessage,
    RoomForwardMessage,
    RoomInfoUpdatedMessage,
    RoomInviteErrorMessage,
    RoomInviteMessage,
    RoomMessageNotificationMessage,
    RoomOccupiedTilesMessage,
    RoomPropertyMessage,
    RoomQueueStatusMessage,
    RoomRatingMessage,
    RoomReadyMessage,
    RoomVisualizationSettingsMessage,
    SanctionStatusEventMessage,
    ScrSendUserInfoMessage,
    SeasonalCalendarDailyOfferMessage,
    SellablePetPalettesMessage,
    ShoutMessage,
    ShowMysteryBoxWaitMessage,
    SilverBalanceMessage,
    SleepMessage,
    SlideObjectBundleMessage,
    SnowWarGameTokensMessageMessage,
    SpecialRoomEffectMessage,
    TargetedOfferEventMessage,
    TargetedOfferNotFoundEventMessage,
    ThumbnailStatusMessage,
    TradeOpenFailedEventPaserMessage,
    TradeSilverFeeMessage,
    TradeSilverSetMessage,
    TradingAcceptEventMessage,
    TradingCloseEventMessage,
    TradingCompletedEventMessage,
    TradingConfirmationEventMessage,
    TradingItemListEventMessage,
    TradingNotOpenEventMessage,
    TradingOpenEventMessage,
    TradingOtherNotAllowedEventMessage,
    TradingYouAreNotAllowedEventMessage,
    UniqueMachineIdMessage,
    UnseenItemsEventMessage,
    UseObjectMessage,
    UserChangeMessage,
    UserEventCatsMessage,
    UserFlatCatsMessage,
    UserObjectMessage,
    UserRemoveMessage,
    UserRightsMessage,
    UsersMessage,
    UserTypingMessage,
    UserUpdateMessage,
    VoucherRedeemErrorMessage,
    VoucherRedeemOkMessage,
    WardrobeMessage,
    WiredFurniActionEventMessage,
    WiredFurniAddonEventMessage,
    WiredFurniConditionEventMessage,
    WiredFurniSelectorEventMessage,
    WiredFurniTriggerEventMessage,
    WiredFurniVariableEventMessage,
    WiredMovementsMessage,
    WiredPermissionsEventMessage,
    WiredRewardResultMessage,
    WiredSaveSuccessEventMessage,
    WiredValidationErrorEventMessage,
    YouAreControllerMessage,
    YouAreNotControllerMessage,
    YouAreNotSpectatorMessage,
    YouAreOwnerMessage,
    YouArePlayingGameMessage,
    YouAreSpectatorMessage,
    YoutubeControlVideoMessage,
    YoutubeDisplayPlaylistsMessage,
    YoutubeDisplayVideoMessage,
    WhisperMessage
} from './incoming';
import { IncomingHeader } from './IncomingHeader';

export const GetIncomingPackets = () => {
    return {
        // Advertisement
        [IncomingHeader.InterstitialMessage]: InterstitialMessage,
        [IncomingHeader.RoomAdErrorMessage]: RoomAdErrorEventMessage,

        // Handshake
        [IncomingHeader.AuthenticationOKMessage]: AuthenticationOKMessage,
        [IncomingHeader.CompleteDiffieHandshakeMessage]: CompleteDiffieHandshakeMessage,
        [IncomingHeader.GenericErrorMessage]: GenericErrorMessage,
        [IncomingHeader.InitDiffieHandshakeMessage]: InitDiffieHandshakeMessage,
        [IncomingHeader.IsFirstLoginOfDayMessage]: IsFirstLoginOfDayMessage,
        [IncomingHeader.NoobnessLevelMessage]: NoobnessLevelMessage,
        [IncomingHeader.PingMessage]: PingMessage,
        [IncomingHeader.UniqueMachineIDMessage]: UniqueMachineIdMessage,
        [IncomingHeader.UserObjectMessage]: UserObjectMessage,
        [IncomingHeader.UserRightsMessage]: UserRightsMessage,

        // Inventory Achievements
        [IncomingHeader.AchievementMessage]: AchievementEventMessage,
        [IncomingHeader.AchievementsMessage]: AchievementsEventMessage,
        [IncomingHeader.AchievementsScoreMessage]: AchievementsScoreEventMessage,

        // Misc
        [IncomingHeader.AvailabilityStatusMessage]: AvailabilityStatusMessage,
        [IncomingHeader.InfoHotelClosedMessage]: InfoHotelClosedMessage,
        [IncomingHeader.InfoHotelClosingMessage]: InfoHotelClosingMessage,
        [IncomingHeader.LoginFailedHotelClosedMessage]: LoginFailedHotelClosedMessage,
        [IncomingHeader.MaintenanceStatusMessage]: MaintenanceStatusMessage,
        [IncomingHeader.ChangeUserNameResultMessage]: ChangeUserNameResultMessage,
        [IncomingHeader.CheckUserNameResultMessage]: CheckUserNameResultMessage,
        [IncomingHeader.FigureUpdateMessage]: FigureUpdateEventMessage,
        [IncomingHeader.WardrobeMessage]: WardrobeMessage,
        [IncomingHeader.CfhSanctionMessage]: CfhSanctionMessage,
        [IncomingHeader.CfhTopicsInitMessage]: CfhTopicsInitMessage,
        [IncomingHeader.SanctionStatusMessage]: SanctionStatusEventMessage,
        [IncomingHeader.CameraPublishStatusMessage]: CameraPublishStatusMessage,
        [IncomingHeader.CameraPurchaseOKMessage]: CameraPurchaseOKMessage,
        [IncomingHeader.CameraStorageUrlMessage]: CameraStorageUrlMessage,
        [IncomingHeader.CompetitionStatusMessage]: CompetitionStatusMessage,
        [IncomingHeader.InitCameraMessage]: InitCameraMessage,
        [IncomingHeader.ThumbnailStatusMessage]: ThumbnailStatusMessage,
        [IncomingHeader.CampaignCalendarDataMessage]: CampaignCalendarDataMessage,
        [IncomingHeader.CampaignCalendarDoorOpenedMessage]: CampaignCalendarDoorOpenedMessage,
        [IncomingHeader.BonusRareInfoMessage]: BonusRareInfoMessage,
        [IncomingHeader.BuildersClubSubscriptionStatusMessage]: BuildersClubSubscriptionStatusMessage,
        [IncomingHeader.BundleDiscountRulesetMessage]: BundleDiscountRulesetMessage,
        [IncomingHeader.CatalogIndexMessage]: CatalogIndexMessage,
        [IncomingHeader.CatalogPageMessage]: CatalogPageMessage,
        [IncomingHeader.CatalogPageWithEarliestExpiryMessage]: CatalogPageWithEarliestExpiryMessage,
        [IncomingHeader.CatalogPublishedMessage]: CatalogPublishedMessage,
        [IncomingHeader.ClubGiftInfoMessage]: ClubGiftInfoEventMessage,
        [IncomingHeader.ClubGiftSelectedMessage]: ClubGiftSelectedEventMessage,
        [IncomingHeader.GiftReceiverNotFoundMessage]: GiftReceiverNotFoundEventMessage,
        [IncomingHeader.GiftWrappingConfigurationMessage]: GiftWrappingConfigurationEventMessage,
        [IncomingHeader.HabboClubExtendOfferMessage]: HabboClubExtendOfferMessage,
        [IncomingHeader.HabboClubOffersMessage]: HabboClubOffersMessage,
        [IncomingHeader.LimitedEditionSoldOutMessage]: LimitedEditionSoldOutEventMessage,
        [IncomingHeader.LimitedOfferAppearingNextMessage]: LimitedOfferAppearingNextMessage,
        [IncomingHeader.NotEnoughBalanceMessage]: NotEnoughBalanceMessage,
        [IncomingHeader.ProductOfferMessage]: ProductOfferEventMessage,
        [IncomingHeader.PurchaseErrorMessage]: PurchaseErrorMessage,
        [IncomingHeader.PurchaseNotAllowedMessage]: PurchaseNotAllowedMessage,
        [IncomingHeader.PurchaseOKMessage]: PurchaseOKMessage,
        [IncomingHeader.RoomAdPurchaseInfoMessage]: RoomAdPurchaseInfoEventMessage,
        [IncomingHeader.SeasonalCalendarDailyOfferMessage]: SeasonalCalendarDailyOfferMessage,
        [IncomingHeader.SellablePetPalettesMessage]: SellablePetPalettesMessage,
        [IncomingHeader.SnowWarGameTokensMessage]: SnowWarGameTokensMessageMessage,
        [IncomingHeader.TargetedOfferMessage]: TargetedOfferEventMessage,
        [IncomingHeader.TargetedOfferNotFoundMessage]: TargetedOfferNotFoundEventMessage,
        [IncomingHeader.VoucherRedeemErrorMessage]: VoucherRedeemErrorMessage,
        [IncomingHeader.VoucherRedeemOkMessage]: VoucherRedeemOkMessage,
        [IncomingHeader.CollectableMintableItemTypesMessage]: CollectableMintableItemTypesMessage,
        [IncomingHeader.CollectibleMintableItemResultMessage]: CollectibleMintableItemResultMessage,
        [IncomingHeader.CollectibleMintingEnabledMessage]: CollectibleMintingEnabledMessage,
        [IncomingHeader.CollectibleMintTokenCountMessage]: CollectibleMintTokenCountMessage,
        [IncomingHeader.CollectibleMintTokenOffersMessage]: CollectibleMintTokenOffersMessage,
        [IncomingHeader.CollectibleWalletAddressesMessage]: CollectibleWalletAddressesMessage,
        [IncomingHeader.EmeraldBalanceMessage]: EmeraldBalanceMessage,
        [IncomingHeader.NftBonusItemClaimResultMessage]: NftBonusItemClaimResultMessage,
        [IncomingHeader.NftCollectionsMessage]: NftCollectionsMessage,
        [IncomingHeader.NftCollectionsScoreMessage]: NftCollectionsScoreMessage,
        [IncomingHeader.NftRewardItemClaimResultMessage]: NftRewardItemClaimResultMessage,
        [IncomingHeader.NftTransferAssetsResultMessage]: NftTransferAssetsResultMessage,
        [IncomingHeader.NftTransferFeeMessage]: NftTransferFeeMessage,
        [IncomingHeader.SilverBalanceMessage]: SilverBalanceMessage,
        [IncomingHeader.AcceptFriendResultMessage]: AcceptFriendResultMessage,
        [IncomingHeader.ConsoleMessageHistoryMessage]: ConsoleMessageHistoryMessage,
        [IncomingHeader.FollowFriendFailedMessage]: FollowFriendFailedMessage,
        [IncomingHeader.FriendListFragmentMessage]: FriendListFragmentMessage,
        [IncomingHeader.FriendListUpdateMessage]: FriendListUpdateMessage,
        [IncomingHeader.FriendNotificationMessage]: FriendNotificationMessage,
        [IncomingHeader.FriendRequestsMessage]: FriendRequestsMessage,
        [IncomingHeader.HabboSearchResultMessage]: HabboSearchResultMessage,
        [IncomingHeader.InstantMessageErrorMessage]: InstantMessageErrorMessage,
        [IncomingHeader.MessengerErrorMessage]: MessengerErrorMessage,
        [IncomingHeader.MessengerInitMessage]: MessengerInitMessage,
        [IncomingHeader.MiniMailNewMessage]: MiniMailNewMessage,
        [IncomingHeader.MiniMailUnreadCountMessage]: MiniMailUnreadCountMessage,
        [IncomingHeader.NewConsoleMessage]: NewConsoleMessageMessage,
        [IncomingHeader.NewFriendRequestMessage]: NewFriendRequestMessage,
        [IncomingHeader.RoomInviteErrorMessage]: RoomInviteErrorMessage,
        [IncomingHeader.RoomInviteMessage]: RoomInviteMessage,
        [IncomingHeader.AvatarEffectActivatedMessage]: AvatarEffectActivatedMessage,
        [IncomingHeader.AvatarEffectAddedMessage]: AvatarEffectAddedMessage,
        [IncomingHeader.AvatarEffectExpiredMessage]: AvatarEffectExpiredMessage,
        [IncomingHeader.AvatarEffectSelectedMessage]: AvatarEffectSelectedMessage,
        [IncomingHeader.AvatarEffectsMessage]: AvatarEffectsMessage,
        [IncomingHeader.BadgePointLimitsMessage]: BadgePointLimitsEventMessage,
        [IncomingHeader.BadgeReceivedMessage]: BadgeReceivedEventMessage,
        [IncomingHeader.BadgesMessage]: BadgesEventMessage,
        [IncomingHeader.IsBadgeRequestFulfilledMessage]: IsBadgeRequestFulfilledEventMessage,
        [IncomingHeader.BotAddedToInventoryMessage]: BotAddedToInventoryEventMessage,
        [IncomingHeader.BotInventoryMessage]: BotInventoryEventMessage,
        [IncomingHeader.BotRemovedFromInventoryMessage]: BotRemovedFromInventoryEventMessage,
        [IncomingHeader.FigureSetIdsMessage]: FigureSetIdsEventMessage,
        [IncomingHeader.FurniListAddOrUpdateMessage]: FurniListAddOrUpdateEventMessage,
        [IncomingHeader.FurniListMessage]: FurniListEventMessage,
        [IncomingHeader.FurniListInvalidateMessage]: FurniListInvalidateEventMessage,
        [IncomingHeader.FurniListRemoveMessage]: FurniListRemoveEventMessage,
        [IncomingHeader.PostItPlacedMessage]: PostItPlacedEventMessage,
        [IncomingHeader.ConfirmBreedingRequestMessage]: ConfirmBreedingRequestEventMessage,
        [IncomingHeader.ConfirmBreedingResultMessage]: ConfirmBreedingResultEventMessage,
        [IncomingHeader.GoToBreedingNestFailureMessage]: GoToBreedingNestFailureEventMessage,
        [IncomingHeader.NestBreedingSuccessMessage]: NestBreedingSuccessEventMessage,
        [IncomingHeader.PetAddedToInventoryMessage]: PetAddedToInventoryEventMessage,
        [IncomingHeader.PetBreedingMessage]: PetBreedingEventMessage,
        [IncomingHeader.PetInventoryMessage]: PetInventoryEventMessage,
        [IncomingHeader.PetReceivedMessage]: PetReceivedMessage,
        [IncomingHeader.PetRemovedFromInventoryMessage]: PetRemovedFromInventoryEventMessage,
        [IncomingHeader.CreditBalanceMessage]: CreditBalanceEventMessage,
        [IncomingHeader.TradeOpenFailedMessage]: TradeOpenFailedEventPaserMessage,
        [IncomingHeader.TradeSilverFeeMessage]: TradeSilverFeeMessage,
        [IncomingHeader.TradeSilverSetMessage]: TradeSilverSetMessage,
        [IncomingHeader.TradingAcceptMessage]: TradingAcceptEventMessage,
        [IncomingHeader.TradingCloseMessage]: TradingCloseEventMessage,
        [IncomingHeader.TradingCompletedMessage]: TradingCompletedEventMessage,
        [IncomingHeader.TradingConfirmationMessage]: TradingConfirmationEventMessage,
        [IncomingHeader.TradingItemListMessage]: TradingItemListEventMessage,
        [IncomingHeader.TradingNotOpenMessage]: TradingNotOpenEventMessage,
        [IncomingHeader.TradingOpenMessage]: TradingOpenEventMessage,
        [IncomingHeader.TradingOtherNotAllowedMessage]: TradingOtherNotAllowedEventMessage,
        [IncomingHeader.TradingYouAreNotAllowedMessage]: TradingYouAreNotAllowedEventMessage,
        [IncomingHeader.CancelMysteryBoxWaitMessage]: CancelMysteryBoxWaitMessage,
        [IncomingHeader.GotMysteryBoxPrizeMessage]: GotMysteryBoxPrizeMessage,
        [IncomingHeader.MysteryBoxKeysMessage]: MysteryBoxKeysMessage,
        [IncomingHeader.ShowMysteryBoxWaitMessage]: ShowMysteryBoxWaitMessage,
        [IncomingHeader.CanCreateRoomEventMessage]: CanCreateRoomEventMessage,
        [IncomingHeader.CanCreateRoomMessage]: CanCreateRoomMessage,
        [IncomingHeader.CategoriesWithVisitorCountMessage]: CategoriesWithVisitorCountMessage,
        [IncomingHeader.CompetitionRoomsDataMessage]: CompetitionRoomsDataMessage,
        [IncomingHeader.ConvertedRoomIdMessage]: ConvertedRoomIdMessage,
        [IncomingHeader.DoorbellMessage]: DoorbellMessage,
        [IncomingHeader.FavouriteChangedMessage]: FavouriteChangedMessage,
        [IncomingHeader.FavouritesMessage]: FavouritesMessage,
        [IncomingHeader.FlatAccessDeniedMessage]: FlatAccessDeniedMessage,
        [IncomingHeader.FlatCreatedMessage]: FlatCreatedMessage,
        [IncomingHeader.GetGuestRoomResultMessage]: GetGuestRoomResultMessage,
        [IncomingHeader.GuestRoomSearchResultMessage]: GuestRoomSearchResultMessage,
        [IncomingHeader.NavigatorSettingsMessage]: NavigatorSettingsMessage,
        [IncomingHeader.OfficialRoomsMessage]: OfficialRoomsMessage,
        [IncomingHeader.PopularRoomTagsResultMessage]: PopularRoomTagsResultMessage,
        [IncomingHeader.RoomEventCancelMessage]: RoomEventCancelMessage,
        [IncomingHeader.RoomEventMessage]: RoomEventMessage,
        [IncomingHeader.RoomInfoUpdatedMessage]: RoomInfoUpdatedMessage,
        [IncomingHeader.RoomRatingMessage]: RoomRatingMessage,
        [IncomingHeader.UserEventCatsMessage]: UserEventCatsMessage,
        [IncomingHeader.UserFlatCatsMessage]: UserFlatCatsMessage,
        [IncomingHeader.NavigatorCollapsedCategoriesMessage]: NavigatorCollapsedCategoriesMessage,
        [IncomingHeader.NavigatorLiftedRoomsMessage]: NavigatorLiftedRoomsMessage,
        [IncomingHeader.NavigatorMetaDataMessage]: NavigatorMetadataMessage,
        [IncomingHeader.NavigatorSavedSearchesMessage]: NavigatorSavedSearchesMessage,
        [IncomingHeader.NavigatorSearchResultBlocksMessage]: NavigatorSearchResultBlocksMessage,
        [IncomingHeader.NewNavigatorPreferencesMessage]: NewNavigatorPreferencesMessage,
        [IncomingHeader.ActivityPointsMessage]: ActivityPointsMessage,
        [IncomingHeader.ClubGiftNotificationMessage]: ClubGiftNotificationEventMessage,
        [IncomingHeader.ElementPointerMessage]: ElementPointerMessage,
        [IncomingHeader.HabboAchievementNotificationMessage]: HabboAchievementNotificationMessage,
        [IncomingHeader.HabboAchievementNotificationMessage]: HabboActivityPointNotificationMessage,
        [IncomingHeader.HabboBroadcastMessage]: HabboBroadcastMessage,
        [IncomingHeader.InfoFeedEnableMessage]: InfoFeedEnableMessage,
        [IncomingHeader.MOTDNotificationMessage]: MOTDNotificationEventMessage,
        [IncomingHeader.NotificationDialogMessage]: NotificationDialogMessage,
        [IncomingHeader.OfferRewardDeliveredMessage]: OfferRewardDeliveredMessage,
        [IncomingHeader.PetLevelNotificationMessage]: PetLevelNotificationEventMessage,
        [IncomingHeader.RestoreClientMessage]: RestoreClientMessage,
        [IncomingHeader.UnseenItemsMessage]: UnseenItemsEventMessage,
        [IncomingHeader.AccountPreferencesMessage]: AccountPreferencesEventMessage,
        [IncomingHeader.BotCommandConfigurationMessage]: BotCommandConfigurationMessage,
        [IncomingHeader.BotErrorMessage]: BotErrorMessage,
        [IncomingHeader.BotForceOpenContextMenuMessage]: BotForceOpenContextMenuMessage,
        [IncomingHeader.BotSkillListUpdateMessage]: BotSkillListUpdateMessage,
        [IncomingHeader.ChatMessage]: ChatMessage,
        [IncomingHeader.WhisperMessage]: WhisperMessage,
        [IncomingHeader.ShoutMessage]: ShoutMessage,
        [IncomingHeader.FloodControlMessage]: FloodControlMessage,
        [IncomingHeader.RemainingMutePeriodMessage]: RemainingMutePeriodMessage,
        [IncomingHeader.RoomChatSettingsMessage]: RoomChatSettingsMessage,
        [IncomingHeader.RoomFilterSettingsMessage]: RoomFilterSettingsMessage,
        [IncomingHeader.UserTypingMessage]: UserTypingMessage,
        [IncomingHeader.BuildersClubPlacementWarningMessage]: BuildersClubPlacementWarningMessage,
        [IncomingHeader.FavoriteMembershipUpdateMessage]: FavoriteMembershipUpdateMessage,
        [IncomingHeader.FloorHeightMapMessage]: FloorHeightMapMessage,
        [IncomingHeader.FurnitureAliasesMessage]: FurnitureAliasesMessage,
        [IncomingHeader.HeightMapMessage]: HeightMapMessage,
        [IncomingHeader.HeightMapUpdateMessage]: HeightMapUpdateMessage,
        [IncomingHeader.ItemAddMessage]: ItemAddMessage,
        [IncomingHeader.ItemDataUpdateMessage]: ItemDataUpdateMessage,
        [IncomingHeader.ItemRemoveMessage]: ItemRemoveMessage,
        [IncomingHeader.ItemsMessage]: ItemsMessage,
        [IncomingHeader.ItemsStateUpdateMessage]: ItemsStateUpdateMessage,
        [IncomingHeader.ItemStateUpdateMessage]: ItemStateUpdateMessage,
        [IncomingHeader.ItemUpdateMessage]: ItemUpdateMessage,
        [IncomingHeader.ObjectAddMessage]: ObjectAddMessage,
        [IncomingHeader.ObjectDataUpdateMessage]: ObjectDataUpdateMessage,
        [IncomingHeader.ObjectRemoveConfirmMessage]: ObjectRemoveConfirmMessage,
        [IncomingHeader.ObjectRemoveMessage]: ObjectRemoveMessage,
        [IncomingHeader.ObjectRemoveMultipleMessage]: ObjectRemoveMultipleMessage,
        [IncomingHeader.ObjectsDataUpdateMessage]: ObjectsDataUpdateMessage,
        [IncomingHeader.ObjectsMessage]: ObjectsMessage,
        [IncomingHeader.ObjectUpdateMessage]: ObjectUpdateMessage,
        [IncomingHeader.RoomEntryInfoMessage]: RoomEntryInfoMessage,
        [IncomingHeader.RoomPropertyMessage]: RoomPropertyMessage,
        [IncomingHeader.RoomVisualizationSettingsMessage]: RoomVisualizationSettingsMessage,
        [IncomingHeader.SlideObjectBundleMessage]: SlideObjectBundleMessage,
        [IncomingHeader.SpecialRoomEffectMessage]: SpecialRoomEffectMessage,
        [IncomingHeader.UserChangeMessage]: UserChangeMessage,
        [IncomingHeader.UserRemoveMessage]: UserRemoveMessage,
        [IncomingHeader.UsersMessage]: UsersMessage,
        [IncomingHeader.UserUpdateMessage]: UserUpdateMessage,
        [IncomingHeader.WiredMovementsMessage]: WiredMovementsMessage,
        [IncomingHeader.AreaHideMessage]: AreaHideMessage,
        [IncomingHeader.CustomStackingHeightUpdateMessage]: CustomStackingHeightUpdateMessage,
        [IncomingHeader.CustomUserNotificationMessage]: CustomUserNotificationMessage,
        [IncomingHeader.DiceValueMessage]: DiceValueMessage,
        [IncomingHeader.FurniRentOrBuyoutOfferMessage]: FurniRentOrBuyoutOfferMessage,
        [IncomingHeader.GuildFurniContextMenuInfoMessage]: GuildFurniContextMenuInfoMessage,
        [IncomingHeader.OneWayDoorStatusMessage]: OneWayDoorStatusMessage,
        [IncomingHeader.OpenPetPackageRequestedMessage]: OpenPetPackageRequestedMessage,
        [IncomingHeader.OpenPetPackageResultMessage]: OpenPetPackageResultMessage,
        [IncomingHeader.PresentOpenedMessage]: PresentOpenedMessage,
        [IncomingHeader.RentableSpaceRentFailedMessage]: RentableSpaceRentFailedMessage,
        [IncomingHeader.RentableSpaceRentOkMessage]: RentableSpaceRentOkMessage,
        [IncomingHeader.RentableSpaceStatusMessage]: RentableSpaceStatusMessage,
        [IncomingHeader.RequestSpamWallPostItMessage]: RequestSpamWallPostItMessage,
        [IncomingHeader.RoomDimmerPresetsMessage]: RoomDimmerPresetsMessage,
        [IncomingHeader.RoomMessageNotificationMessage]: RoomMessageNotificationMessage,
        [IncomingHeader.YoutubeControlVideoMessage]: YoutubeControlVideoMessage,
        [IncomingHeader.YoutubeDisplayPlaylistsMessage]: YoutubeDisplayPlaylistsMessage,
        [IncomingHeader.YoutubeDisplayVideoMessage]: YoutubeDisplayVideoMessage,
        [IncomingHeader.RoomEntryTileMessage]: RoomEntryTileMessage,
        [IncomingHeader.RoomOccupiedTilesMessage]: RoomOccupiedTilesMessage,
        [IncomingHeader.YouAreControllerMessage]: YouAreControllerMessage,
        [IncomingHeader.YouAreNotControllerMessage]: YouAreNotControllerMessage,
        [IncomingHeader.YouAreOwnerMessage]: YouAreOwnerMessage,
        [IncomingHeader.PetBreedingResultMessage]: PetBreedingResultEventMessage,
        [IncomingHeader.PetCommandsMessage]: PetCommandsMessage,
        [IncomingHeader.PetExperienceMessage]: PetExperienceMessage,
        [IncomingHeader.PetFigureUpdateMessage]: PetFigureUpdateMessage,
        [IncomingHeader.PetInfoMessage]: PetInfoMessage,
        [IncomingHeader.PetLevelUpdateMessage]: PetLevelUpdateMessage,
        [IncomingHeader.PetPlacingErrorMessage]: PetPlacingErrorMessage,
        [IncomingHeader.PetRespectFailedMessage]: PetRespectFailedMessage,
        [IncomingHeader.PetStatusUpdateMessage]: PetStatusUpdateMessage,
        [IncomingHeader.CantConnectMessage]: CantConnectMessage,
        [IncomingHeader.CloseConnectionMessage]: CloseConnectionMessage,
        [IncomingHeader.FlatAccessibleMessage]: FlatAccessibleMessage,
        [IncomingHeader.GamePlayerValueMessage]: GamePlayerValueMessage,
        [IncomingHeader.HanditemConfigurationMessage]: HanditemConfigurationMessage,
        [IncomingHeader.OpenConnectionMessage]: OpenConnectionMessage,
        [IncomingHeader.RoomForwardMessage]: RoomForwardMessage,
        [IncomingHeader.RoomQueueStatusMessage]: RoomQueueStatusMessage,
        [IncomingHeader.RoomReadyMessage]: RoomReadyMessage,
        [IncomingHeader.YouAreNotSpectatorMessage]: YouAreNotSpectatorMessage,
        [IncomingHeader.YouArePlayingGameMessage]: YouArePlayingGameMessage,
        [IncomingHeader.YouAreSpectatorMessage]: YouAreSpectatorMessage,
        [IncomingHeader.OpenMessage]: OpenEventMessage,
        [IncomingHeader.WiredFurniActionMessage]: WiredFurniActionEventMessage,
        [IncomingHeader.WiredFurniAddonMessage]: WiredFurniAddonEventMessage,
        [IncomingHeader.WiredFurniConditionMessage]: WiredFurniConditionEventMessage,
        [IncomingHeader.WiredFurniSelectorMessage]: WiredFurniSelectorEventMessage,
        [IncomingHeader.WiredFurniTriggerMessage]: WiredFurniTriggerEventMessage,
        [IncomingHeader.WiredFurniVariableMessage]: WiredFurniVariableEventMessage,
        [IncomingHeader.WiredRewardResultMessage]: WiredRewardResultMessage,
        [IncomingHeader.WiredSaveSuccessMessage]: WiredSaveSuccessEventMessage,
        [IncomingHeader.WiredValidationErrorMessage]: WiredValidationErrorEventMessage,
        [IncomingHeader.AccountSafetyLockStatusChangeMessage]: AccountSafetyLockStatusChangeMessage,
        [IncomingHeader.ApproveNameMessage]: ApproveNameMessage,
        [IncomingHeader.ChangeEmailResultMessage]: ChangeEmailResultEventMessage,
        [IncomingHeader.EmailStatusResultMessage]: EmailStatusResultEventMessage,
        [IncomingHeader.ExtendedProfileChangedMessage]: ExtendedProfileChangedMessage,
        [IncomingHeader.ScrSendUserInfoMessage]: ScrSendUserInfoMessage,
        [IncomingHeader.CreditVaultStatusMessage]: CreditVaultStatusMessage,
        [IncomingHeader.IncomeRewardClaimResponseMessage]: IncomeRewardClaimResponseMessage,
        [IncomingHeader.IncomeRewardStatusMessage]: IncomeRewardStatusMessage,

        // Room Action
        [IncomingHeader.AvatarEffectMessage]: AvatarEffectMessage,
        [IncomingHeader.CarryObjectMessage]: CarryObjectMessage,
        [IncomingHeader.DanceMessage]: DanceMessage,
        [IncomingHeader.ExpressionMessage]: ExpressionMessage,
        [IncomingHeader.SleepMessage]: SleepMessage,
        [IncomingHeader.UseObjectMessage]: UseObjectMessage,

        // Tracking
        [IncomingHeader.LatencyPingResponseMessage]: LatencyPingResponseMessage,

        // Userdefinedroomevents Wiredmenu
        [IncomingHeader.WiredPermissionsMessage]: WiredPermissionsEventMessage,
    } as Record<number, IncomingPacketConstructor>;
};
