import type { IncomingPacketConstructor } from '@nitrodevco/nitro-api';

import {
    AcceptFriendResultMessage,
    AccountPreferencesEventMessage,
    AccountSafetyLockStatusChangeMessage,
    AchievementEventMessage,
    AchievementsEventMessage,
    AchievementsScoreEventMessage,
    ActivityPointsMessage,
    ApproveNameMessage,
    AreaHideMessage,
    AuthenticationOKMessage,
    AvailabilityStatusMessage,
    AvatarEffectActivatedMessage,
    AvatarEffectAddedMessage,
    AvatarEffectExpiredMessage,
    AvatarEffectMessage,
    AvatarEffectSelectedMessage,
    AvatarEffectsMessage,
    BadgePointLimitsEventMessage,
    BadgeReceivedEventMessage,
    BadgesEventMessage,
    BonusRareInfoMessage,
    BotAddedToInventoryEventMessage,
    BotCommandConfigurationMessage,
    BotErrorMessage,
    BotForceOpenContextMenuMessage,
    BotInventoryEventMessage,
    BotRemovedFromInventoryEventMessage,
    BotSkillListUpdateMessage,
    BuildersClubPlacementWarningMessage,
    BuildersClubSubscriptionStatusMessage,
    BundleDiscountRulesetMessage,
    CameraPublishStatusMessage,
    CameraPurchaseOKMessage,
    CameraStorageUrlMessage,
    CampaignCalendarDataMessage,
    CampaignCalendarDoorOpenedMessage,
    CancelMysteryBoxWaitMessage,
    CanCreateRoomEventMessage,
    CanCreateRoomMessage,
    CantConnectMessage,
    CarryObjectMessage,
    CatalogIndexMessage,
    CatalogPageMessage,
    CatalogPageWithEarliestExpiryMessage,
    CatalogPublishedMessage,
    CategoriesWithVisitorCountMessage,
    CfhSanctionMessage,
    CfhTopicsInitMessage,
    ChangeEmailResultEventMessage,
    ChangeUserNameResultMessage,
    ChatMessage,
    CheckUserNameResultMessage,
    CloseConnectionMessage,
    ClubGiftInfoEventMessage,
    ClubGiftNotificationEventMessage,
    ClubGiftSelectedEventMessage,
    CollectableMintableItemTypesMessage,
    CollectibleMintableItemResultMessage,
    CollectibleMintingEnabledMessage,
    CollectibleMintTokenCountMessage,
    CollectibleMintTokenOffersMessage,
    CollectibleWalletAddressesMessage,
    CompetitionRoomsDataMessage,
    CompetitionStatusMessage,
    CompleteDiffieHandshakeMessage,
    ConfirmBreedingRequestEventMessage,
    ConfirmBreedingResultEventMessage,
    ConsoleMessageHistoryMessage,
    ConvertedRoomIdMessage,
    CreditBalanceEventMessage,
    CreditVaultStatusMessage,
    CustomStackingHeightUpdateMessage,
    CustomUserNotificationMessage,
    DanceMessage,
    DiceValueMessage,
    DoorbellMessage,
    ElementPointerMessage,
    EmailStatusResultEventMessage,
    EmeraldBalanceMessage,
    ExpressionMessage,
    ExtendedProfileChangedMessage,
    FavoriteMembershipUpdateMessage,
    FavouriteChangedMessage,
    FavouritesMessage,
    FigureSetIdsEventMessage,
    FigureUpdateEventMessage,
    FlatAccessDeniedMessage,
    FlatAccessibleMessage,
    FlatCreatedMessage,
    FloodControlMessage,
    FloorHeightMapMessage,
    FollowFriendFailedMessage,
    FriendListFragmentMessage,
    FriendListUpdateMessage,
    FriendNotificationMessage,
    FriendRequestsMessage,
    FurniListAddOrUpdateEventMessage,
    FurniListEventMessage,
    FurniListInvalidateEventMessage,
    FurniListRemoveEventMessage,
    FurniRentOrBuyoutOfferMessage,
    FurnitureAliasesMessage,
    GamePlayerValueMessage,
    GenericErrorMessage,
    GetGuestRoomResultMessage,
    GiftReceiverNotFoundEventMessage,
    GiftWrappingConfigurationEventMessage,
    GotMysteryBoxPrizeMessage,
    GoToBreedingNestFailureEventMessage,
    GuestRoomSearchResultMessage,
    GuildFurniContextMenuInfoMessage,
    HabboAchievementNotificationMessage,
    HabboActivityPointNotificationMessage,
    HabboBroadcastMessage,
    HabboClubExtendOfferMessage,
    HabboClubOffersMessage,
    HabboSearchResultMessage,
    HanditemConfigurationMessage,
    HeightMapMessage,
    HeightMapUpdateMessage,
    IncomeRewardClaimResponseMessage,
    IncomeRewardStatusMessage,
    InfoFeedEnableMessage,
    InfoHotelClosedMessage,
    InfoHotelClosingMessage,
    InitCameraMessage,
    InitDiffieHandshakeMessage,
    InstantMessageErrorMessage,
    InterstitialMessage,
    IsBadgeRequestFulfilledEventMessage,
    IsFirstLoginOfDayMessage,
    ItemAddMessage,
    ItemDataUpdateMessage,
    ItemRemoveMessage,
    ItemsMessage,
    ItemsStateUpdateMessage,
    ItemStateUpdateMessage,
    ItemUpdateMessage,
    LatencyPingResponseMessage,
    LimitedEditionSoldOutEventMessage,
    LimitedOfferAppearingNextMessage,
    LoginFailedHotelClosedMessage,
    MaintenanceStatusMessage,
    MessengerErrorMessage,
    MessengerInitMessage,
    MiniMailNewMessage,
    MiniMailUnreadCountMessage,
    MOTDNotificationEventMessage,
    MysteryBoxKeysMessage,
    NavigatorCollapsedCategoriesMessage,
    NavigatorLiftedRoomsMessage,
    NavigatorMetadataMessage,
    NavigatorSavedSearchesMessage,
    NavigatorSearchResultBlocksMessage,
    NavigatorSettingsMessage,
    NestBreedingSuccessEventMessage,
    NewConsoleMessageMessage,
    NewFriendRequestMessage,
    NewNavigatorPreferencesMessage,
    NftBonusItemClaimResultMessage,
    NftCollectionsMessage,
    NftCollectionsScoreMessage,
    NftRewardItemClaimResultMessage,
    NftTransferAssetsResultMessage,
    NftTransferFeeMessage,
    NoobnessLevelMessage,
    NotEnoughBalanceMessage,
    NotificationDialogMessage,
    ObjectAddMessage,
    ObjectDataUpdateMessage,
    ObjectRemoveConfirmMessage,
    ObjectRemoveMessage,
    ObjectRemoveMultipleMessage,
    ObjectsDataUpdateMessage,
    ObjectsMessage,
    ObjectUpdateMessage,
    OfferRewardDeliveredMessage,
    OfficialRoomsMessage,
    OneWayDoorStatusMessage,
    OpenConnectionMessage,
    OpenEventMessage,
    OpenPetPackageRequestedMessage,
    OpenPetPackageResultMessage,
    PetAddedToInventoryEventMessage,
    PetBreedingEventMessage,
    PetBreedingResultEventMessage,
    PetCommandsMessage,
    PetExperienceMessage,
    PetFigureUpdateMessage,
    PetInfoMessage,
    PetInventoryEventMessage,
    PetLevelNotificationEventMessage,
    PetLevelUpdateMessage,
    PetPlacingErrorMessage,
    PetReceivedMessage,
    PetRemovedFromInventoryEventMessage,
    PetRespectFailedMessage,
    PetStatusUpdateMessage,
    PingMessage,
    PopularRoomTagsResultMessage,
    PostItPlacedEventMessage,
    PresentOpenedMessage,
    ProductOfferEventMessage,
    PurchaseErrorMessage,
    PurchaseNotAllowedMessage,
    PurchaseOKMessage,
    RemainingMutePeriodMessage,
    RentableSpaceRentFailedMessage,
    RentableSpaceRentOkMessage,
    RentableSpaceStatusMessage,
    RequestSpamWallPostItMessage,
    RestoreClientMessage,
    RoomAdErrorEventMessage,
    RoomAdPurchaseInfoEventMessage,
    RoomChatSettingsMessage,
    RoomDimmerPresetsMessage,
    RoomEntryInfoMessage,
    RoomEntryTileMessage,
    RoomEventCancelMessage,
    RoomEventMessage,
    RoomFilterSettingsMessage,
    RoomForwardMessage,
    RoomInfoUpdatedMessage,
    RoomInviteErrorMessage,
    RoomInviteMessage,
    RoomMessageNotificationMessage,
    RoomOccupiedTilesMessage,
    RoomPropertyMessage,
    RoomQueueStatusMessage,
    RoomRatingMessage,
    RoomReadyMessage,
    RoomVisualizationSettingsMessage,
    SanctionStatusEventMessage,
    ScrSendUserInfoMessage,
    SeasonalCalendarDailyOfferMessage,
    SellablePetPalettesMessage,
    ShoutMessage,
    ShowMysteryBoxWaitMessage,
    SilverBalanceMessage,
    SleepMessage,
    SlideObjectBundleMessage,
    SnowWarGameTokensMessageMessage,
    SpecialRoomEffectMessage,
    TargetedOfferEventMessage,
    TargetedOfferNotFoundEventMessage,
    ThumbnailStatusMessage,
    TradeOpenFailedEventPaserMessage,
    TradeSilverFeeMessage,
    TradeSilverSetMessage,
    TradingAcceptEventMessage,
    TradingCloseEventMessage,
    TradingCompletedEventMessage,
    TradingConfirmationEventMessage,
    TradingItemListEventMessage,
    TradingNotOpenEventMessage,
    TradingOpenEventMessage,
    TradingOtherNotAllowedEventMessage,
    TradingYouAreNotAllowedEventMessage,
    UniqueMachineIdMessage,
    UnseenItemsEventMessage,
    UseObjectMessage,
    UserChangeMessage,
    UserEventCatsMessage,
    UserFlatCatsMessage,
    UserObjectMessage,
    UserRemoveMessage,
    UserRightsMessage,
    UsersMessage,
    UserTypingMessage,
    UserUpdateMessage,
    VoucherRedeemErrorMessage,
    VoucherRedeemOkMessage,
    WardrobeMessage,
    WiredFurniActionEventMessage,
    WiredFurniAddonEventMessage,
    WiredFurniConditionEventMessage,
    WiredFurniSelectorEventMessage,
    WiredFurniTriggerEventMessage,
    WiredFurniVariableEventMessage,
    WiredMovementsMessage,
    WiredPermissionsEventMessage,
    WiredRewardResultMessage,
    WiredSaveSuccessEventMessage,
    WiredValidationErrorEventMessage,
    YouAreControllerMessage,
    YouAreNotControllerMessage,
    YouAreNotSpectatorMessage,
    YouAreOwnerMessage,
    YouArePlayingGameMessage,
    YouAreSpectatorMessage,
    YoutubeControlVideoMessage,
    YoutubeDisplayPlaylistsMessage,
    YoutubeDisplayVideoMessage,
} from './incoming';
import { WhisperMessage } from './incoming';
import { IncomingHeader } from './IncomingHeader';

export const GetIncomingPackets = () => {
    return {
        // Advertisement
        [IncomingHeader.InterstitialMessageComposer]: InterstitialMessage,
        [IncomingHeader.RoomAdErrorComposer]: RoomAdErrorEventMessage,

        // Handshake
        [IncomingHeader.AuthenticationOKMessageComposer]: AuthenticationOKMessage,
        [IncomingHeader.CompleteDiffieHandshakeComposer]: CompleteDiffieHandshakeMessage,
        [IncomingHeader.GenericErrorComposer]: GenericErrorMessage,
        [IncomingHeader.InitDiffieHandshakeComposer]: InitDiffieHandshakeMessage,
        [IncomingHeader.IsFirstLoginOfDayComposer]: IsFirstLoginOfDayMessage,
        [IncomingHeader.NoobnessLevelMessageComposer]: NoobnessLevelMessage,
        [IncomingHeader.PingMessageComposer]: PingMessage,
        [IncomingHeader.UniqueMachineIDComposer]: UniqueMachineIdMessage,
        [IncomingHeader.UserObjectComposer]: UserObjectMessage,
        [IncomingHeader.UserRightsMessageComposer]: UserRightsMessage,

        // Inventory Achievements
        [IncomingHeader.AchievementComposer]: AchievementEventMessage,
        [IncomingHeader.AchievementsComposer]: AchievementsEventMessage,
        [IncomingHeader.AchievementsScoreComposer]: AchievementsScoreEventMessage,

        // Misc
        [IncomingHeader.AvailabilityStatusMessageComposer]: AvailabilityStatusMessage,
        [IncomingHeader.InfoHotelClosedMessageComposer]: InfoHotelClosedMessage,
        [IncomingHeader.InfoHotelClosingMessageComposer]: InfoHotelClosingMessage,
        [IncomingHeader.LoginFailedHotelClosedMessageComposer]: LoginFailedHotelClosedMessage,
        [IncomingHeader.MaintenanceStatusMessageComposer]: MaintenanceStatusMessage,
        [IncomingHeader.ChangeUserNameResultMessageComposer]: ChangeUserNameResultMessage,
        [IncomingHeader.CheckUserNameResultMessageComposer]: CheckUserNameResultMessage,
        [IncomingHeader.FigureUpdateComposer]: FigureUpdateEventMessage,
        [IncomingHeader.WardrobeMessageComposer]: WardrobeMessage,
        [IncomingHeader.CfhSanctionMessageComposer]: CfhSanctionMessage,
        [IncomingHeader.CfhTopicsInitMessageComposer]: CfhTopicsInitMessage,
        [IncomingHeader.SanctionStatusComposer]: SanctionStatusEventMessage,
        [IncomingHeader.CameraPublishStatusMessageComposer]: CameraPublishStatusMessage,
        [IncomingHeader.CameraPurchaseOKMessageComposer]: CameraPurchaseOKMessage,
        [IncomingHeader.CameraStorageUrlMessageComposer]: CameraStorageUrlMessage,
        [IncomingHeader.CompetitionStatusMessageComposer]: CompetitionStatusMessage,
        [IncomingHeader.InitCameraMessageComposer]: InitCameraMessage,
        [IncomingHeader.ThumbnailStatusMessageComposer]: ThumbnailStatusMessage,
        [IncomingHeader.CampaignCalendarDataMessageComposer]: CampaignCalendarDataMessage,
        [IncomingHeader.CampaignCalendarDoorOpenedMessageComposer]: CampaignCalendarDoorOpenedMessage,
        [IncomingHeader.BonusRareInfoMessageComposer]: BonusRareInfoMessage,
        [IncomingHeader.BuildersClubSubscriptionStatusMessageComposer]: BuildersClubSubscriptionStatusMessage,
        [IncomingHeader.BundleDiscountRulesetMessageComposer]: BundleDiscountRulesetMessage,
        [IncomingHeader.CatalogIndexMessageComposer]: CatalogIndexMessage,
        [IncomingHeader.CatalogPageMessageComposer]: CatalogPageMessage,
        [IncomingHeader.CatalogPageWithEarliestExpiryMessageComposer]: CatalogPageWithEarliestExpiryMessage,
        [IncomingHeader.CatalogPublishedMessageComposer]: CatalogPublishedMessage,
        [IncomingHeader.ClubGiftInfoComposer]: ClubGiftInfoEventMessage,
        [IncomingHeader.ClubGiftSelectedComposer]: ClubGiftSelectedEventMessage,
        [IncomingHeader.GiftReceiverNotFoundComposer]: GiftReceiverNotFoundEventMessage,
        [IncomingHeader.GiftWrappingConfigurationComposer]: GiftWrappingConfigurationEventMessage,
        [IncomingHeader.HabboClubExtendOfferMessageComposer]: HabboClubExtendOfferMessage,
        [IncomingHeader.HabboClubOffersMessageComposer]: HabboClubOffersMessage,
        [IncomingHeader.LimitedEditionSoldOutComposer]: LimitedEditionSoldOutEventMessage,
        [IncomingHeader.LimitedOfferAppearingNextMessageComposer]: LimitedOfferAppearingNextMessage,
        [IncomingHeader.NotEnoughBalanceMessageComposer]: NotEnoughBalanceMessage,
        [IncomingHeader.ProductOfferComposer]: ProductOfferEventMessage,
        [IncomingHeader.PurchaseErrorMessageComposer]: PurchaseErrorMessage,
        [IncomingHeader.PurchaseNotAllowedMessageComposer]: PurchaseNotAllowedMessage,
        [IncomingHeader.PurchaseOKMessageComposer]: PurchaseOKMessage,
        [IncomingHeader.RoomAdPurchaseInfoComposer]: RoomAdPurchaseInfoEventMessage,
        [IncomingHeader.SeasonalCalendarDailyOfferMessageComposer]: SeasonalCalendarDailyOfferMessage,
        [IncomingHeader.SellablePetPalettesMessageComposer]: SellablePetPalettesMessage,
        [IncomingHeader.SnowWarGameTokensMessageComposer]: SnowWarGameTokensMessageMessage,
        [IncomingHeader.TargetedOfferComposer]: TargetedOfferEventMessage,
        [IncomingHeader.TargetedOfferNotFoundComposer]: TargetedOfferNotFoundEventMessage,
        [IncomingHeader.VoucherRedeemErrorMessageComposer]: VoucherRedeemErrorMessage,
        [IncomingHeader.VoucherRedeemOkMessageComposer]: VoucherRedeemOkMessage,
        [IncomingHeader.CollectableMintableItemTypesMessageComposer]: CollectableMintableItemTypesMessage,
        [IncomingHeader.CollectibleMintableItemResultMessageComposer]: CollectibleMintableItemResultMessage,
        [IncomingHeader.CollectibleMintingEnabledMessageComposer]: CollectibleMintingEnabledMessage,
        [IncomingHeader.CollectibleMintTokenCountMessageComposer]: CollectibleMintTokenCountMessage,
        [IncomingHeader.CollectibleMintTokenOffersMessageComposer]: CollectibleMintTokenOffersMessage,
        [IncomingHeader.CollectibleWalletAddressesMessageComposer]: CollectibleWalletAddressesMessage,
        [IncomingHeader.EmeraldBalanceMessageComposer]: EmeraldBalanceMessage,
        [IncomingHeader.NftBonusItemClaimResultMessageComposer]: NftBonusItemClaimResultMessage,
        [IncomingHeader.NftCollectionsMessageComposer]: NftCollectionsMessage,
        [IncomingHeader.NftCollectionsScoreMessageComposer]: NftCollectionsScoreMessage,
        [IncomingHeader.NftRewardItemClaimResultMessageComposer]: NftRewardItemClaimResultMessage,
        [IncomingHeader.NftTransferAssetsResultMessageComposer]: NftTransferAssetsResultMessage,
        [IncomingHeader.NftTransferFeeMessageComposer]: NftTransferFeeMessage,
        [IncomingHeader.SilverBalanceMessageComposer]: SilverBalanceMessage,
        [IncomingHeader.AcceptFriendResultComposer]: AcceptFriendResultMessage,
        [IncomingHeader.ConsoleMessageHistoryComposer]: ConsoleMessageHistoryMessage,
        [IncomingHeader.FollowFriendFailedComposer]: FollowFriendFailedMessage,
        [IncomingHeader.FriendListFragmentMessageComposer]: FriendListFragmentMessage,
        [IncomingHeader.FriendListUpdateComposer]: FriendListUpdateMessage,
        [IncomingHeader.FriendNotificationComposer]: FriendNotificationMessage,
        [IncomingHeader.FriendRequestsComposer]: FriendRequestsMessage,
        [IncomingHeader.HabboSearchResultComposer]: HabboSearchResultMessage,
        [IncomingHeader.InstantMessageErrorComposer]: InstantMessageErrorMessage,
        [IncomingHeader.MessengerErrorComposer]: MessengerErrorMessage,
        [IncomingHeader.MessengerInitComposer]: MessengerInitMessage,
        [IncomingHeader.MiniMailNewMessageComposer]: MiniMailNewMessage,
        [IncomingHeader.MiniMailUnreadCountComposer]: MiniMailUnreadCountMessage,
        [IncomingHeader.NewConsoleMessageComposer]: NewConsoleMessageMessage,
        [IncomingHeader.NewFriendRequestComposer]: NewFriendRequestMessage,
        [IncomingHeader.RoomInviteErrorComposer]: RoomInviteErrorMessage,
        [IncomingHeader.RoomInviteComposer]: RoomInviteMessage,
        [IncomingHeader.AvatarEffectActivatedMessageComposer]: AvatarEffectActivatedMessage,
        [IncomingHeader.AvatarEffectAddedMessageComposer]: AvatarEffectAddedMessage,
        [IncomingHeader.AvatarEffectExpiredMessageComposer]: AvatarEffectExpiredMessage,
        [IncomingHeader.AvatarEffectSelectedMessageComposer]: AvatarEffectSelectedMessage,
        [IncomingHeader.AvatarEffectsMessageComposer]: AvatarEffectsMessage,
        [IncomingHeader.BadgePointLimitsComposer]: BadgePointLimitsEventMessage,
        [IncomingHeader.BadgeReceivedComposer]: BadgeReceivedEventMessage,
        [IncomingHeader.BadgesComposer]: BadgesEventMessage,
        [IncomingHeader.IsBadgeRequestFulfilledComposer]: IsBadgeRequestFulfilledEventMessage,
        [IncomingHeader.BotAddedToInventoryComposer]: BotAddedToInventoryEventMessage,
        [IncomingHeader.BotInventoryComposer]: BotInventoryEventMessage,
        [IncomingHeader.BotRemovedFromInventoryComposer]: BotRemovedFromInventoryEventMessage,
        [IncomingHeader.FigureSetIdsComposer]: FigureSetIdsEventMessage,
        [IncomingHeader.FurniListAddOrUpdateComposer]: FurniListAddOrUpdateEventMessage,
        [IncomingHeader.FurniListComposer]: FurniListEventMessage,
        [IncomingHeader.FurniListInvalidateComposer]: FurniListInvalidateEventMessage,
        [IncomingHeader.FurniListRemoveComposer]: FurniListRemoveEventMessage,
        [IncomingHeader.PostItPlacedComposer]: PostItPlacedEventMessage,
        [IncomingHeader.ConfirmBreedingRequestComposer]: ConfirmBreedingRequestEventMessage,
        [IncomingHeader.ConfirmBreedingResultComposer]: ConfirmBreedingResultEventMessage,
        [IncomingHeader.GoToBreedingNestFailureComposer]: GoToBreedingNestFailureEventMessage,
        [IncomingHeader.NestBreedingSuccessComposer]: NestBreedingSuccessEventMessage,
        [IncomingHeader.PetAddedToInventoryComposer]: PetAddedToInventoryEventMessage,
        [IncomingHeader.PetBreedingComposer]: PetBreedingEventMessage,
        [IncomingHeader.PetInventoryComposer]: PetInventoryEventMessage,
        [IncomingHeader.PetReceivedMessageComposer]: PetReceivedMessage,
        [IncomingHeader.PetRemovedFromInventoryComposer]: PetRemovedFromInventoryEventMessage,
        [IncomingHeader.CreditBalanceComposer]: CreditBalanceEventMessage,
        [IncomingHeader.TradeOpenFailedComposer]: TradeOpenFailedEventPaserMessage,
        [IncomingHeader.TradeSilverFeeMessageComposer]: TradeSilverFeeMessage,
        [IncomingHeader.TradeSilverSetMessageComposer]: TradeSilverSetMessage,
        [IncomingHeader.TradingAcceptComposer]: TradingAcceptEventMessage,
        [IncomingHeader.TradingCloseComposer]: TradingCloseEventMessage,
        [IncomingHeader.TradingCompletedComposer]: TradingCompletedEventMessage,
        [IncomingHeader.TradingConfirmationComposer]: TradingConfirmationEventMessage,
        [IncomingHeader.TradingItemListComposer]: TradingItemListEventMessage,
        [IncomingHeader.TradingNotOpenComposer]: TradingNotOpenEventMessage,
        [IncomingHeader.TradingOpenComposer]: TradingOpenEventMessage,
        [IncomingHeader.TradingOtherNotAllowedComposer]: TradingOtherNotAllowedEventMessage,
        [IncomingHeader.TradingYouAreNotAllowedComposer]: TradingYouAreNotAllowedEventMessage,
        [IncomingHeader.CancelMysteryBoxWaitMessageComposer]: CancelMysteryBoxWaitMessage,
        [IncomingHeader.GotMysteryBoxPrizeMessageComposer]: GotMysteryBoxPrizeMessage,
        [IncomingHeader.MysteryBoxKeysMessageComposer]: MysteryBoxKeysMessage,
        [IncomingHeader.ShowMysteryBoxWaitMessageComposer]: ShowMysteryBoxWaitMessage,
        [IncomingHeader.CanCreateRoomEventComposer]: CanCreateRoomEventMessage,
        [IncomingHeader.CanCreateRoomComposer]: CanCreateRoomMessage,
        [IncomingHeader.CategoriesWithVisitorCountComposer]: CategoriesWithVisitorCountMessage,
        [IncomingHeader.CompetitionRoomsDataMessageComposer]: CompetitionRoomsDataMessage,
        [IncomingHeader.ConvertedRoomIdComposer]: ConvertedRoomIdMessage,
        [IncomingHeader.DoorbellMessageComposer]: DoorbellMessage,
        [IncomingHeader.FavouriteChangedComposer]: FavouriteChangedMessage,
        [IncomingHeader.FavouritesComposer]: FavouritesMessage,
        [IncomingHeader.FlatAccessDeniedMessageComposer]: FlatAccessDeniedMessage,
        [IncomingHeader.FlatCreatedComposer]: FlatCreatedMessage,
        [IncomingHeader.GetGuestRoomResultComposer]: GetGuestRoomResultMessage,
        [IncomingHeader.GuestRoomSearchResultComposer]: GuestRoomSearchResultMessage,
        [IncomingHeader.NavigatorSettingsComposer]: NavigatorSettingsMessage,
        [IncomingHeader.OfficialRoomsComposer]: OfficialRoomsMessage,
        [IncomingHeader.PopularRoomTagsResultComposer]: PopularRoomTagsResultMessage,
        [IncomingHeader.RoomEventCancelComposer]: RoomEventCancelMessage,
        [IncomingHeader.RoomEventComposer]: RoomEventMessage,
        [IncomingHeader.RoomInfoUpdatedComposer]: RoomInfoUpdatedMessage,
        [IncomingHeader.RoomRatingComposer]: RoomRatingMessage,
        [IncomingHeader.UserEventCatsComposer]: UserEventCatsMessage,
        [IncomingHeader.UserFlatCatsComposer]: UserFlatCatsMessage,
        [IncomingHeader.NavigatorCollapsedCategoriesMessageComposer]: NavigatorCollapsedCategoriesMessage,
        [IncomingHeader.NavigatorLiftedRoomsComposer]: NavigatorLiftedRoomsMessage,
        [IncomingHeader.NavigatorMetaDataComposer]: NavigatorMetadataMessage,
        [IncomingHeader.NavigatorSavedSearchesComposer]: NavigatorSavedSearchesMessage,
        [IncomingHeader.NavigatorSearchResultBlocksComposer]: NavigatorSearchResultBlocksMessage,
        [IncomingHeader.NewNavigatorPreferencesComposer]: NewNavigatorPreferencesMessage,
        [IncomingHeader.ActivityPointsMessageComposer]: ActivityPointsMessage,
        [IncomingHeader.ClubGiftNotificationComposer]: ClubGiftNotificationEventMessage,
        [IncomingHeader.ElementPointerMessageComposer]: ElementPointerMessage,
        [IncomingHeader.HabboAchievementNotificationMessageComposer]: HabboAchievementNotificationMessage,
        [IncomingHeader.HabboAchievementNotificationMessageComposer]: HabboActivityPointNotificationMessage,
        [IncomingHeader.HabboBroadcastMessageComposer]: HabboBroadcastMessage,
        [IncomingHeader.InfoFeedEnableMessageComposer]: InfoFeedEnableMessage,
        [IncomingHeader.MOTDNotificationComposer]: MOTDNotificationEventMessage,
        [IncomingHeader.NotificationDialogMessageComposer]: NotificationDialogMessage,
        [IncomingHeader.OfferRewardDeliveredMessageComposer]: OfferRewardDeliveredMessage,
        [IncomingHeader.PetLevelNotificationComposer]: PetLevelNotificationEventMessage,
        [IncomingHeader.RestoreClientMessageComposer]: RestoreClientMessage,
        [IncomingHeader.UnseenItemsComposer]: UnseenItemsEventMessage,
        [IncomingHeader.AccountPreferencesComposer]: AccountPreferencesEventMessage,
        [IncomingHeader.BotCommandConfigurationComposer]: BotCommandConfigurationMessage,
        [IncomingHeader.BotErrorComposer]: BotErrorMessage,
        [IncomingHeader.BotForceOpenContextMenuComposer]: BotForceOpenContextMenuMessage,
        [IncomingHeader.BotSkillListUpdateComposer]: BotSkillListUpdateMessage,
        [IncomingHeader.ChatMessageComposer]: ChatMessage,
        [IncomingHeader.WhisperMessageComposer]: WhisperMessage,
        [IncomingHeader.ShoutMessageComposer]: ShoutMessage,
        [IncomingHeader.FloodControlMessageComposer]: FloodControlMessage,
        [IncomingHeader.RemainingMutePeriodComposer]: RemainingMutePeriodMessage,
        [IncomingHeader.RoomChatSettingsMessageComposer]: RoomChatSettingsMessage,
        [IncomingHeader.RoomFilterSettingsMessageComposer]: RoomFilterSettingsMessage,
        [IncomingHeader.UserTypingMessageComposer]: UserTypingMessage,
        [IncomingHeader.BuildersClubPlacementWarningMessageComposer]: BuildersClubPlacementWarningMessage,
        [IncomingHeader.FavoriteMembershipUpdateMessageComposer]: FavoriteMembershipUpdateMessage,
        [IncomingHeader.FloorHeightMapMessageComposer]: FloorHeightMapMessage,
        [IncomingHeader.FurnitureAliasesMessageComposer]: FurnitureAliasesMessage,
        [IncomingHeader.HeightMapMessageComposer]: HeightMapMessage,
        [IncomingHeader.HeightMapUpdateMessageComposer]: HeightMapUpdateMessage,
        [IncomingHeader.ItemAddMessageComposer]: ItemAddMessage,
        [IncomingHeader.ItemDataUpdateMessageComposer]: ItemDataUpdateMessage,
        [IncomingHeader.ItemRemoveMessageComposer]: ItemRemoveMessage,
        [IncomingHeader.ItemsMessageComposer]: ItemsMessage,
        [IncomingHeader.ItemsStateUpdateMessageComposer]: ItemsStateUpdateMessage,
        [IncomingHeader.ItemStateUpdateMessageComposer]: ItemStateUpdateMessage,
        [IncomingHeader.ItemUpdateMessageComposer]: ItemUpdateMessage,
        [IncomingHeader.ObjectAddMessageComposer]: ObjectAddMessage,
        [IncomingHeader.ObjectDataUpdateMessageComposer]: ObjectDataUpdateMessage,
        [IncomingHeader.ObjectRemoveConfirmMessageComposer]: ObjectRemoveConfirmMessage,
        [IncomingHeader.ObjectRemoveMessageComposer]: ObjectRemoveMessage,
        [IncomingHeader.ObjectRemoveMultipleMessageComposer]: ObjectRemoveMultipleMessage,
        [IncomingHeader.ObjectsDataUpdateMessageComposer]: ObjectsDataUpdateMessage,
        [IncomingHeader.ObjectsMessageComposer]: ObjectsMessage,
        [IncomingHeader.ObjectUpdateMessageComposer]: ObjectUpdateMessage,
        [IncomingHeader.RoomEntryInfoMessageComposer]: RoomEntryInfoMessage,
        [IncomingHeader.RoomPropertyMessageComposer]: RoomPropertyMessage,
        [IncomingHeader.RoomVisualizationSettingsComposer]: RoomVisualizationSettingsMessage,
        [IncomingHeader.SlideObjectBundleMessageComposer]: SlideObjectBundleMessage,
        [IncomingHeader.SpecialRoomEffectMessageComposer]: SpecialRoomEffectMessage,
        [IncomingHeader.UserChangeMessageComposer]: UserChangeMessage,
        [IncomingHeader.UserRemoveMessageComposer]: UserRemoveMessage,
        [IncomingHeader.UsersMessageComposer]: UsersMessage,
        [IncomingHeader.UserUpdateMessageComposer]: UserUpdateMessage,
        [IncomingHeader.WiredMovementsMessageComposer]: WiredMovementsMessage,
        [IncomingHeader.AreaHideMessageComposer]: AreaHideMessage,
        [IncomingHeader.CustomStackingHeightUpdateMessageComposer]: CustomStackingHeightUpdateMessage,
        [IncomingHeader.CustomUserNotificationMessageComposer]: CustomUserNotificationMessage,
        [IncomingHeader.DiceValueMessageComposer]: DiceValueMessage,
        [IncomingHeader.FurniRentOrBuyoutOfferMessageComposer]: FurniRentOrBuyoutOfferMessage,
        [IncomingHeader.GuildFurniContextMenuInfoMessageComposer]: GuildFurniContextMenuInfoMessage,
        [IncomingHeader.OneWayDoorStatusMessageComposer]: OneWayDoorStatusMessage,
        [IncomingHeader.OpenPetPackageRequestedMessageComposer]: OpenPetPackageRequestedMessage,
        [IncomingHeader.OpenPetPackageResultMessageComposer]: OpenPetPackageResultMessage,
        [IncomingHeader.PresentOpenedMessageComposer]: PresentOpenedMessage,
        [IncomingHeader.RentableSpaceRentFailedMessageComposer]: RentableSpaceRentFailedMessage,
        [IncomingHeader.RentableSpaceRentOkMessageComposer]: RentableSpaceRentOkMessage,
        [IncomingHeader.RentableSpaceStatusMessageComposer]: RentableSpaceStatusMessage,
        [IncomingHeader.RequestSpamWallPostItMessageComposer]: RequestSpamWallPostItMessage,
        [IncomingHeader.RoomDimmerPresetsMessageComposer]: RoomDimmerPresetsMessage,
        [IncomingHeader.RoomMessageNotificationMessageComposer]: RoomMessageNotificationMessage,
        [IncomingHeader.YoutubeControlVideoMessageComposer]: YoutubeControlVideoMessage,
        [IncomingHeader.YoutubeDisplayPlaylistsMessageComposer]: YoutubeDisplayPlaylistsMessage,
        [IncomingHeader.YoutubeDisplayVideoMessageComposer]: YoutubeDisplayVideoMessage,
        [IncomingHeader.RoomEntryTileMessageComposer]: RoomEntryTileMessage,
        [IncomingHeader.RoomOccupiedTilesMessageComposer]: RoomOccupiedTilesMessage,
        [IncomingHeader.YouAreControllerMessageComposer]: YouAreControllerMessage,
        [IncomingHeader.YouAreNotControllerMessageComposer]: YouAreNotControllerMessage,
        [IncomingHeader.YouAreOwnerMessageComposer]: YouAreOwnerMessage,
        [IncomingHeader.PetBreedingResultComposer]: PetBreedingResultEventMessage,
        [IncomingHeader.PetCommandsMessageComposer]: PetCommandsMessage,
        [IncomingHeader.PetExperienceComposer]: PetExperienceMessage,
        [IncomingHeader.PetFigureUpdateComposer]: PetFigureUpdateMessage,
        [IncomingHeader.PetInfoMessageComposer]: PetInfoMessage,
        [IncomingHeader.PetLevelUpdateComposer]: PetLevelUpdateMessage,
        [IncomingHeader.PetPlacingErrorComposer]: PetPlacingErrorMessage,
        [IncomingHeader.PetRespectFailedComposer]: PetRespectFailedMessage,
        [IncomingHeader.PetStatusUpdateComposer]: PetStatusUpdateMessage,
        [IncomingHeader.CantConnectMessageComposer]: CantConnectMessage,
        [IncomingHeader.CloseConnectionMessageComposer]: CloseConnectionMessage,
        [IncomingHeader.FlatAccessibleMessageComposer]: FlatAccessibleMessage,
        [IncomingHeader.GamePlayerValueMessageComposer]: GamePlayerValueMessage,
        [IncomingHeader.HanditemConfigurationMessageComposer]: HanditemConfigurationMessage,
        [IncomingHeader.OpenConnectionMessageComposer]: OpenConnectionMessage,
        [IncomingHeader.RoomForwardMessageComposer]: RoomForwardMessage,
        [IncomingHeader.RoomQueueStatusMessageComposer]: RoomQueueStatusMessage,
        [IncomingHeader.RoomReadyMessageComposer]: RoomReadyMessage,
        [IncomingHeader.YouAreNotSpectatorMessageComposer]: YouAreNotSpectatorMessage,
        [IncomingHeader.YouArePlayingGameMessageComposer]: YouArePlayingGameMessage,
        [IncomingHeader.YouAreSpectatorMessageComposer]: YouAreSpectatorMessage,
        [IncomingHeader.OpenComposer]: OpenEventMessage,
        [IncomingHeader.WiredFurniActionComposer]: WiredFurniActionEventMessage,
        [IncomingHeader.WiredFurniAddonComposer]: WiredFurniAddonEventMessage,
        [IncomingHeader.WiredFurniConditionComposer]: WiredFurniConditionEventMessage,
        [IncomingHeader.WiredFurniSelectorComposer]: WiredFurniSelectorEventMessage,
        [IncomingHeader.WiredFurniTriggerComposer]: WiredFurniTriggerEventMessage,
        [IncomingHeader.WiredFurniVariableComposer]: WiredFurniVariableEventMessage,
        [IncomingHeader.WiredRewardResultMessageComposer]: WiredRewardResultMessage,
        [IncomingHeader.WiredSaveSuccessComposer]: WiredSaveSuccessEventMessage,
        [IncomingHeader.WiredValidationErrorComposer]: WiredValidationErrorEventMessage,
        [IncomingHeader.AccountSafetyLockStatusChangeMessageComposer]: AccountSafetyLockStatusChangeMessage,
        [IncomingHeader.ApproveNameMessageComposer]: ApproveNameMessage,
        [IncomingHeader.ChangeEmailResultComposer]: ChangeEmailResultEventMessage,
        [IncomingHeader.EmailStatusResultComposer]: EmailStatusResultEventMessage,
        [IncomingHeader.ExtendedProfileChangedMessageComposer]: ExtendedProfileChangedMessage,
        [IncomingHeader.ScrSendUserInfoComposer]: ScrSendUserInfoMessage,
        [IncomingHeader.CreditVaultStatusMessageComposer]: CreditVaultStatusMessage,
        [IncomingHeader.IncomeRewardClaimResponseMessageComposer]: IncomeRewardClaimResponseMessage,
        [IncomingHeader.IncomeRewardStatusMessageComposer]: IncomeRewardStatusMessage,

        // Room Action
        [IncomingHeader.AvatarEffectMessageComposer]: AvatarEffectMessage,
        [IncomingHeader.CarryObjectMessageComposer]: CarryObjectMessage,
        [IncomingHeader.DanceMessageComposer]: DanceMessage,
        [IncomingHeader.ExpressionMessageComposer]: ExpressionMessage,
        [IncomingHeader.SleepMessageComposer]: SleepMessage,
        [IncomingHeader.UseObjectMessageComposer]: UseObjectMessage,

        // Tracking
        [IncomingHeader.LatencyPingResponseMessageComposer]: LatencyPingResponseMessage,

        // Userdefinedroomevents Wiredmenu
        [IncomingHeader.WiredPermissionsComposer]: WiredPermissionsEventMessage,
    } as Record<number, IncomingPacketConstructor>;
};
