export enum RoomObjectOperationType {
    OBJECT_UNDEFINED = 'OBJECT_UNDEFINED',
    OBJECT_MOVE = 'OBJECT_MOVE',
    OBJECT_PLACE = 'OBJECT_PLACE',
    OBJECT_ROTATE_POSITIVE = 'OBJECT_ROTATE_POSITIVE',
    OBJECT_ROTATE_NEGATIVE = 'OBJECT_ROTATE_NEGATIVE',
    OBJECT_MOVE_TO = 'OBJECT_MOVE_TO',
    OBJECT_PLACE_TO = 'OBJECT_PLACE_TO',
    OBJECT_PICKUP = 'OBJECT_PICKUP',
    OBJECT_PICKUP_BOT = 'OBJECT_PICKUP_BOT',
    OBJECT_PICKUP_PET = 'OBJECT_PICKUP_PET',
    OBJECT_EJECT = 'OBJECT_EJECT',
    OBJECT_SAVE_STUFF_DATA = 'OBJECT_SAVE_STUFF_DATA',
}
