/**
 * The Flash client's `HabboAvatarAnimation.xml`: per action, the frames every figure part steps
 * through and the body part offsets that go with them. An action that lists a part with several
 * frames is what makes that part animate - the companion pets (`pt`/`ptr`/`ptl`) and the
 * animated clothing cycle eight `std` frames while the avatar just stands. Generated by
 * `scripts/generate-avatar-animations.ts`; regenerate rather than edit.
 */
import { AvatarBodyPartType, AvatarFigurePartType, IAssetAvatarAnimation } from '@nitrodevco/nitro-api';

export const HabboAvatarAnimations: IAssetAvatarAnimation[] = [
    {
        id: 'Move',
        parts: [
            {
                setType: AvatarFigurePartType.Body,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.BodySwim,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Ss,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Legs,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Shoes,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftHand,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftHandSwim,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightHand,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightHandSwim,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscRight,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.CoatChest,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessoryExtra,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.ChestAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.WaistAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Hair,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.HairBig,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.EyeAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.FaceAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Pet,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetRight,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Misc,
                frames: [
                    { number: 0, assetPartDefinition: 'wlk' },
                    { number: 1, assetPartDefinition: 'wlk' },
                    { number: 2, assetPartDefinition: 'wlk' },
                    { number: 3, assetPartDefinition: 'wlk' },
                ],
            },
        ],
    },
    {
        id: 'Wave',
        parts: [
            {
                setType: AvatarFigurePartType.LeftHand,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftHandSwim,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                    { number: 2, assetPartDefinition: 'wav' },
                    { number: 3, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.Pet,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetRight,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.Misc,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                    { number: 1, assetPartDefinition: 'wav' },
                ],
            },
        ],
    },
    {
        id: 'Talk',
        parts: [
            {
                setType: AvatarFigurePartType.Head,
                frames: [
                    { number: 0, assetPartDefinition: 'spk' },
                    { number: 1, assetPartDefinition: 'spk' },
                ],
            },
            {
                setType: AvatarFigurePartType.Face,
                frames: [
                    { number: 0, assetPartDefinition: 'spk' },
                    { number: 1, assetPartDefinition: 'spk' },
                ],
            },
            {
                setType: AvatarFigurePartType.FaceAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'spk' },
                    { number: 1, assetPartDefinition: 'spk' },
                ],
            },
        ],
    },
    {
        id: 'Swim',
        parts: [
            {
                setType: AvatarFigurePartType.BodySwim,
                frames: [
                    { number: 0, assetPartDefinition: 'swm' },
                    { number: 1, assetPartDefinition: 'swm' },
                    { number: 2, assetPartDefinition: 'swm' },
                    { number: 3, assetPartDefinition: 'swm' },
                ],
            },
            {
                setType: AvatarFigurePartType.Ss,
                frames: [
                    { number: 0, assetPartDefinition: 'swm' },
                    { number: 1, assetPartDefinition: 'swm' },
                    { number: 2, assetPartDefinition: 'swm' },
                    { number: 3, assetPartDefinition: 'swm' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftHandSwim,
                frames: [
                    { number: 0, assetPartDefinition: 'swm' },
                    { number: 1, assetPartDefinition: 'swm' },
                    { number: 2, assetPartDefinition: 'swm' },
                    { number: 3, assetPartDefinition: 'swm' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightHandSwim,
                frames: [
                    { number: 0, assetPartDefinition: 'swm' },
                    { number: 1, assetPartDefinition: 'swm' },
                    { number: 2, assetPartDefinition: 'swm' },
                    { number: 3, assetPartDefinition: 'swm' },
                ],
            },
        ],
    },
    {
        id: 'Float',
        parts: [
            {
                setType: AvatarFigurePartType.BodySwim,
                frames: [
                    { number: 3, assetPartDefinition: 'sws' },
                    { number: 3, assetPartDefinition: 'sws' },
                    { number: 2, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                    { number: 0, assetPartDefinition: 'sws' },
                ],
            },
            {
                setType: AvatarFigurePartType.Ss,
                frames: [
                    { number: 0, assetPartDefinition: 'sws' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftHandSwim,
                frames: [
                    { number: 0, assetPartDefinition: 'sws' },
                    { number: 0, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                    { number: 2, assetPartDefinition: 'sws' },
                    { number: 3, assetPartDefinition: 'sws' },
                    { number: 3, assetPartDefinition: 'sws' },
                    { number: 2, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightHandSwim,
                frames: [
                    { number: 0, assetPartDefinition: 'sws' },
                    { number: 0, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                    { number: 2, assetPartDefinition: 'sws' },
                    { number: 3, assetPartDefinition: 'sws' },
                    { number: 3, assetPartDefinition: 'sws' },
                    { number: 2, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                    { number: 1, assetPartDefinition: 'sws' },
                ],
            },
        ],
    },
    {
        id: 'Sign',
        parts: [
            {
                setType: AvatarFigurePartType.LeftHand,
                frames: [
                    { number: 0, assetPartDefinition: 'sig' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftHandItem,
                frames: [
                    { number: 0, assetPartDefinition: 'sig' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'wav' },
                ],
            },
        ],
    },
    {
        id: 'Respect',
        parts: [
            {
                setType: AvatarFigurePartType.LeftHand,
                frames: [
                    { number: 0, assetPartDefinition: 'respect', repeats: 15 },
                    { number: 1, assetPartDefinition: 'respect', repeats: 15 },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wav', repeats: 15 },
                    { number: 1, assetPartDefinition: 'wav', repeats: 15 },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'wav', repeats: 15 },
                    { number: 1, assetPartDefinition: 'wav', repeats: 15 },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'wav', repeats: 15 },
                    { number: 1, assetPartDefinition: 'wav', repeats: 15 },
                ],
            },
        ],
    },
    {
        id: 'Blow',
        parts: [
            {
                setType: AvatarFigurePartType.RightHand,
                frames: [
                    { number: 0, assetPartDefinition: 'blw', repeats: 10 },
                    { number: 1, assetPartDefinition: 'blw', repeats: 10 },
                ],
            },
            {
                setType: AvatarFigurePartType.RightSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'drk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'drk' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscRight,
                frames: [
                    { number: 0, assetPartDefinition: 'drk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightHandItem,
                frames: [
                    { number: 0, assetPartDefinition: '' },
                ],
            },
            {
                setType: AvatarFigurePartType.Eyes,
                frames: [
                    { number: 0, assetPartDefinition: 'std', repeats: 10 },
                    { number: 0, assetPartDefinition: 'eyb', repeats: 10 },
                ],
            },
            {
                setType: AvatarFigurePartType.Face,
                frames: [
                    { number: 0, assetPartDefinition: 'std', repeats: 10 },
                    { number: 0, assetPartDefinition: 'blw', repeats: 10 },
                ],
            },
        ],
    },
    {
        id: 'Laugh',
        parts: [
            {
                setType: AvatarFigurePartType.RightHand,
                frames: [
                    { number: 0, assetPartDefinition: 'blw' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'drk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'drk' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscRight,
                frames: [
                    { number: 0, assetPartDefinition: 'drk' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightHandItem,
                frames: [
                    { number: 0, assetPartDefinition: '' },
                ],
            },
            {
                setType: AvatarFigurePartType.Eyes,
                frames: [
                    { number: 0, assetPartDefinition: 'std', repeats: 2 },
                ],
            },
            {
                setType: AvatarFigurePartType.Face,
                frames: [
                    { number: 0, assetPartDefinition: 'sml' },
                ],
            },
        ],
        offsets: {
            frames: [
                {
                    id: 0,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                        { id: 1, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                        { id: 3, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                        { id: 5, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                        { id: 7, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 1 } ] },
                    ],
                },
                {
                    id: 1,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                        { id: 1, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                        { id: 3, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                        { id: 5, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                        { id: 7, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 0 } ] },
                    ],
                },
            ],
        },
    },
    {
        id: 'SnowWarRun',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 3, assetPartDefinition: 'swrun' },
                    { number: 2, assetPartDefinition: 'swrun' },
                    { number: 1, assetPartDefinition: 'swrun' },
                    { number: 0, assetPartDefinition: 'swrun' },
                ],
            },
        ],
    },
    {
        id: 'SnowWarDieFront',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'swdie' },
                    { number: 0, assetPartDefinition: 'swdie' },
                    { number: 1, assetPartDefinition: 'swdie' },
                    { number: 1, assetPartDefinition: 'swdie', repeats: 100 },
                ],
            },
        ],
        offsets: {
            frames: [
                {
                    id: 0,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 4 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 4 } ] },
                    ],
                },
                {
                    id: 1,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 4 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 4 } ] },
                    ],
                },
                {
                    id: 2,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                    ],
                },
                {
                    id: 3,
                    repeats: 100,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                    ],
                },
            ],
        },
    },
    {
        id: 'SnowWarDieBack',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 2, assetPartDefinition: 'swdie' },
                    { number: 2, assetPartDefinition: 'swdie' },
                    { number: 3, assetPartDefinition: 'swdie' },
                    { number: 3, assetPartDefinition: 'swdie', repeats: 100 },
                ],
            },
        ],
        offsets: {
            frames: [
                {
                    id: 0,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 4 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 4 } ] },
                    ],
                },
                {
                    id: 1,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 4 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -10, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 10, dy: 4 } ] },
                    ],
                },
                {
                    id: 2,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                    ],
                },
                {
                    id: 3,
                    repeats: 100,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: -100, dy: 5 } ] },
                    ],
                },
            ],
        },
    },
    {
        id: 'SnowWarPick',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'swpick' },
                ],
            },
        ],
        offsets: {
            frames: [
                {
                    id: 0,
                    directions: [
                        { id: 0, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                        { id: 1, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                        { id: 2, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                        { id: 3, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                        { id: 4, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                        { id: 5, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                        { id: 6, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                        { id: 7, bodyParts: [ { id: AvatarBodyPartType.Head, dx: 0, dy: 3 } ] },
                    ],
                },
            ],
        },
    },
    {
        id: 'SnowWarThrow',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'swthrow' },
                    { number: 0, assetPartDefinition: 'swthrow' },
                    { number: 1, assetPartDefinition: 'swthrow' },
                    { number: 1, assetPartDefinition: 'swthrow' },
                    { number: 1, assetPartDefinition: 'swthrow' },
                    { number: 1, assetPartDefinition: 'swthrow' },
                    { number: 1, assetPartDefinition: 'swthrow' },
                    { number: 1, assetPartDefinition: 'swthrow' },
                    { number: 0, assetPartDefinition: 'swthrow', repeats: 100 },
                ],
            },
        ],
    },
    {
        id: 'Default',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.CoatChest,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.Misc,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscRight,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessoryExtra,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.WaistAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.Pet,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetRight,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
        ],
    },
    {
        id: 'Lay',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.CoatChest,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.Misc,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscRight,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessoryExtra,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.WaistAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.Pet,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetRight,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'lay' },
                    { number: 1, assetPartDefinition: 'lay' },
                    { number: 2, assetPartDefinition: 'lay' },
                    { number: 3, assetPartDefinition: 'lay' },
                    { number: 4, assetPartDefinition: 'lay' },
                    { number: 5, assetPartDefinition: 'lay' },
                    { number: 6, assetPartDefinition: 'lay' },
                    { number: 7, assetPartDefinition: 'lay' },
                ],
            },
        ],
    },
    {
        id: 'Sleep',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.CoatChest,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.Misc,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightCoatSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.MiscRight,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessoryExtra,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.WaistAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.Pet,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetRight,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'std' },
                    { number: 1, assetPartDefinition: 'std' },
                    { number: 2, assetPartDefinition: 'std' },
                    { number: 3, assetPartDefinition: 'std' },
                    { number: 4, assetPartDefinition: 'std' },
                    { number: 5, assetPartDefinition: 'std' },
                    { number: 6, assetPartDefinition: 'std' },
                    { number: 7, assetPartDefinition: 'std' },
                ],
            },
        ],
    },
    {
        id: 'Sit',
        parts: [
            {
                setType: AvatarFigurePartType.Chest,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.CoatChest,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.Misc,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.LeftSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.RightSleeve,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.HeadAccessoryExtra,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.WaistAccessory,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.Pet,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetRight,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
            {
                setType: AvatarFigurePartType.PetLeft,
                frames: [
                    { number: 0, assetPartDefinition: 'sit' },
                    { number: 1, assetPartDefinition: 'sit' },
                    { number: 2, assetPartDefinition: 'sit' },
                    { number: 3, assetPartDefinition: 'sit' },
                    { number: 4, assetPartDefinition: 'sit' },
                    { number: 5, assetPartDefinition: 'sit' },
                    { number: 6, assetPartDefinition: 'sit' },
                    { number: 7, assetPartDefinition: 'sit' },
                ],
            },
        ],
    },
];
