// Generated by scripts/generate-barrels.ts - run it instead of editing by hand.
export * from './InfostandBot';
export * from './InfostandFurni';
export * from './InfostandPet';
export * from './RoomObjectInfostandWidget';
