import { IncomingPacketConstructor } from '@nitrodevco/nitro-api';

import {
    AcceptFriendResultMessage,
    AccountPreferencesEventMessage,
    AccountSafetyLockStatusChangeMessage,
    AchievementEventMessage,
    AchievementsEventMessage,
    AchievementsScoreEventMessage,
    ActivityPointsMessage,
    ApproveNameMessage,
    AreaHideMessage,
    AuthenticationOKMessage,
    AvailabilityStatusMessage,
    AvatarEffectActivatedMessage,
    AvatarEffectAddedMessage,
    AvatarEffectExpiredMessage,
    AvatarEffectMessage,
    AvatarEffectSelectedMessage,
    AvatarEffectsMessage,
    BadgePointLimitsEventMessage,
    BadgeReceivedEventMessage,
    BadgesEventMessage,
    BannedUsersFromRoomEventMessage,
    BlockListMessage,
    BlockUserUpdateMessage,
    BonusRareInfoMessage,
    BotAddedToInventoryEventMessage,
    BotCommandConfigurationMessage,
    BotErrorMessage,
    BotForceOpenContextMenuMessage,
    BotInventoryEventMessage,
    BotRemovedFromInventoryEventMessage,
    BotSkillListUpdateMessage,
    BuildersClubFurniCountMessage,
    BuildersClubPlacementWarningMessage,
    BuildersClubSubscriptionStatusMessage,
    BundleDiscountRulesetMessage,
    CameraPublishStatusMessage,
    CameraPurchaseOKMessage,
    CameraStorageUrlMessage,
    CampaignCalendarDataMessage,
    CampaignCalendarDoorOpenedMessage,
    CancelMysteryBoxWaitMessage,
    CanCreateRoomEventMessage,
    CanCreateRoomMessage,
    CantConnectMessage,
    CarryObjectMessage,
    CatalogIndexMessage,
    CatalogPageMessage,
    CatalogPageWithEarliestExpiryMessage,
    CatalogPublishedMessage,
    CategoriesWithVisitorCountMessage,
    CfhChatlogMessage,
    CfhSanctionMessage,
    CfhTopicsInitMessage,
    ChangeEmailResultEventMessage,
    ChangeUserNameResultMessage,
    ChatMessage,
    CheckUserNameResultMessage,
    ChestPreferencesUpdateSuccessMessage,
    CitizenshipVipOfferPromoEnabledMessage,
    ClaimProductResultMessage,
    CloseConnectionMessage,
    ClubGiftInfoEventMessage,
    ClubGiftNotificationEventMessage,
    ClubGiftSelectedEventMessage,
    CoinsChestContentsMessage,
    CollectableMintableItemTypesMessage,
    CollectibleMintableItemResultMessage,
    CollectibleMintingEnabledMessage,
    CollectibleMintTokenCountMessage,
    CollectibleMintTokenOffersMessage,
    CollectibleWalletAddressesMessage,
    CommunityVoteReceivedMessage,
    CompetitionRoomsDataMessage,
    CompetitionStatusMessage,
    CompleteDiffieHandshakeMessage,
    ConfigurationItemStatesMessage,
    ConfirmBreedingRequestEventMessage,
    ConfirmBreedingResultEventMessage,
    ConsoleMessageHistoryMessage,
    ConvertedRoomIdMessage,
    CraftableProductsMessage,
    CraftingRecipeMessage,
    CraftingRecipesAvailableMessage,
    CraftingResultMessage,
    CreditBalanceEventMessage,
    CustomUserNotificationMessage,
    DanceMessage,
    DiceValueMessage,
    DisconnectReasonMessage,
    DoorbellMessage,
    ElementPointerMessage,
    EmailStatusResultEventMessage,
    EmeraldBalanceMessage,
    ErrorReportMessage,
    ExpressionMessage,
    ExtendedProfileChangedMessage,
    FavoriteMembershipUpdateMessage,
    FavouriteChangedMessage,
    FavouritesMessage,
    FigureSetIdsEventMessage,
    FigureUpdateEventMessage,
    FindFriendsProcessResultMessage,
    FlatAccessDeniedMessage,
    FlatAccessibleMessage,
    FlatControllerAddedEventMessage,
    FlatControllerRemovedEventMessage,
    FlatControllersEventMessage,
    FlatCreatedMessage,
    FloodControlMessage,
    FloorHeightMapMessage,
    FollowFriendFailedMessage,
    FriendFurniCancelLockMessage,
    FriendFurniOtherLockConfirmedMessage,
    FriendFurniStartConfirmationMessage,
    FriendListFragmentMessage,
    FriendListUpdateMessage,
    FriendNotificationMessage,
    FriendRequestsMessage,
    FurniListAddOrUpdateEventMessage,
    FurniListEventMessage,
    FurniListInvalidateEventMessage,
    FurniListRemoveEventMessage,
    FurniRentOrBuyoutOfferMessage,
    FurnitureAliasesMessage,
    Game2AccountGameStatusMessage,
    Game2GameCancelledMessage,
    Game2GameDirectoryStatusMessage,
    Game2GameNotFoundMessage,
    Game2InArenaQueueMessage,
    Game2JoiningGameFailedMessage,
    Game2StartCounterMessage,
    Game2StartingGameFailedMessage,
    Game2StopCounterMessage,
    Game2UserBlockedMessage,
    Game2UserLeftGameMessage,
    GamePlayerValueMessage,
    GenericErrorMessage,
    GetGuestRoomResultMessage,
    GiftReceiverNotFoundEventMessage,
    GiftWrappingConfigurationEventMessage,
    GotMysteryBoxPrizeMessage,
    GoToBreedingNestFailureEventMessage,
    GuestRoomSearchResultMessage,
    GuideSessionMessage,
    GuildFurniContextMenuInfoMessage,
    GuildMembershipsMessage,
    HabbiconInfoMessage,
    HabbiconShopDataMessage,
    HabboAchievementNotificationMessage,
    HabboActivityPointNotificationMessage,
    HabboBroadcastMessage,
    HabboClubExtendOfferMessage,
    HabboClubOffersMessage,
    HabboGroupBadgesMessage,
    HabboGroupDetailsMessage,
    HabboSearchResultMessage,
    HabboUserBadgesMessage,
    HandItemReceivedMessage,
    HasClaimedProductResponseMessage,
    HeightMapMessage,
    HeightMapUpdateMessage,
    IdentityAccountsMessage,
    IgnoredUsersMessage,
    IgnoreResultMessage,
    IncomeRewardClaimResponseMessage,
    IncomeRewardNotificationMessage,
    IncomeRewardStatusMessage,
    InfoFeedEnableMessage,
    InfoHotelClosedMessage,
    InfoHotelClosingMessage,
    InitCameraMessage,
    InitDiffieHandshakeMessage,
    InstantMessageErrorMessage,
    InterstitialMessage,
    IsBadgeRequestFulfilledEventMessage,
    IsFirstLoginOfDayMessage,
    ItemAddMessage,
    ItemDataUpdateMessage,
    ItemRemoveMessage,
    ItemsChestContentsChunkMessage,
    ItemsChestContentsUpdatedMessage,
    ItemsMessage,
    ItemsStateUpdateMessage,
    ItemStateUpdateMessage,
    ItemUpdateMessage,
    JukeboxSongDisksMessage,
    LatencyPingResponseMessage,
    LimitedEditionSoldOutEventMessage,
    LimitedOfferAppearingNextMessage,
    LoginFailedHotelClosedMessage,
    LtdRaffleEnteredMessage,
    LtdRaffleResultMessage,
    MaintenanceStatusMessage,
    MarketplaceBuyOfferResultMessage,
    MarketplaceCancelAllOffersResultMessage,
    MarketplaceCancelOfferResultMessage,
    MarketplaceCanMakeOfferResultMessage,
    MarketplaceClearOwnHistoryResultMessage,
    MarketplaceConfigurationMessage,
    MarketplaceItemStatsMessage,
    MarketplaceMakeOfferResultMessage,
    MarketPlaceOffersMessage,
    MarketPlaceOwnOffersMessage,
    MessengerErrorMessage,
    MessengerInitMessage,
    MiniMailNewMessage,
    MiniMailUnreadCountMessage,
    ModeratorCautionMessage,
    ModeratorRoomInfoMessage,
    ModeratorToolPreferencesMessage,
    ModeratorUserInfoMessage,
    MOTDNotificationEventMessage,
    MuteAllInRoomMessage,
    MysteryBoxKeysMessage,
    NavigatorCollapsedCategoriesMessage,
    NavigatorLiftedRoomsMessage,
    NavigatorMetadataMessage,
    NavigatorSavedSearchesMessage,
    NavigatorSearchResultBlocksMessage,
    NavigatorSettingsMessage,
    NestBreedingSuccessEventMessage,
    NewConsoleMessageMessage,
    NewFriendRequestMessage,
    NewNavigatorPreferencesMessage,
    NewUserExperienceGiftOfferMessage,
    NewUserExperienceNotCompleteMessage,
    NftBonusItemClaimResultMessage,
    NftClaimResultMessage,
    NftClaimsMessage,
    NftCollectionsMessage,
    NftCollectionsScoreMessage,
    NftRewardItemClaimResultMessage,
    NftStoreOffersMessage,
    NftStorePurchaseMessage,
    NftTransferAssetsResultMessage,
    NftTransferFeeMessage,
    NoobnessLevelMessage,
    NoSuchFlatMessage,
    NotEnoughBalanceMessage,
    NotificationDialogMessage,
    NowPlayingMessage,
    ObjectAddMessage,
    ObjectDataUpdateMessage,
    ObjectRemoveConfirmMessage,
    ObjectRemoveMessage,
    ObjectRemoveMultipleMessage,
    ObjectsDataUpdateMessage,
    ObjectsMessage,
    ObjectUpdateMessage,
    OfferRewardDeliveredMessage,
    OfficialRoomsMessage,
    OfficialSongIdMessage,
    OneWayDoorStatusMessage,
    OpenChestMessage,
    OpenConnectionMessage,
    OpenEventMessage,
    OpenPetPackageRequestedMessage,
    OpenPetPackageResultMessage,
    PerkAllowancesMessage,
    PetAddedToInventoryEventMessage,
    PetBreedingEventMessage,
    PetBreedingResultEventMessage,
    PetCommandsMessage,
    PetExperienceMessage,
    PetFigureUpdateMessage,
    PetInfoMessage,
    PetInventoryEventMessage,
    PetLevelNotificationEventMessage,
    PetLevelUpdateMessage,
    PetPlacingErrorMessage,
    PetReceivedMessage,
    PetRemovedFromInventoryEventMessage,
    PetRespectFailedMessage,
    PetRespectNotificationEventMessage,
    PetStatusUpdateMessage,
    PetSupplementedNotificationEventMessage,
    PingMessage,
    PlayListMessage,
    PollContentsEventMessage,
    PollErrorEventMessage,
    PollOfferEventMessage,
    PopularRoomTagsResultMessage,
    PostItPlacedEventMessage,
    PostMessage,
    PresentOpenedMessage,
    ProductOfferEventMessage,
    PurchaseErrorMessage,
    PurchaseNotAllowedMessage,
    PurchaseOKMessage,
    QuestionAnsweredEventMessage,
    QuestionEventMessage,
    QuestionFinishedEventMessage,
    RecyclerFinishedMessage,
    RecyclerPrizesMessage,
    RecyclerStatusMessage,
    RedeemNftLootBoxResultMessage,
    RedeemNftLootBoxStateMessage,
    RelationshipStatusInfoEventMessage,
    RemainingMutePeriodMessage,
    RentableSpaceRentFailedMessage,
    RentableSpaceRentOkMessage,
    RentableSpaceStatusMessage,
    RequestSpamWallPostItMessage,
    RespectNotificationMessage,
    RestoreClientMessage,
    RoomAdErrorEventMessage,
    RoomAdPurchaseInfoEventMessage,
    RoomChatlogMessage,
    RoomChatSettingsMessage,
    RoomDimmerPresetsMessage,
    RoomEntryInfoMessage,
    RoomEntryTileMessage,
    RoomEventCancelMessage,
    RoomEventMessage,
    RoomFilterSettingsMessage,
    RoomForwardMessage,
    RoomInfoUpdatedMessage,
    RoomInviteErrorMessage,
    RoomInviteMessage,
    RoomMessageNotificationMessage,
    RoomOccupiedTilesMessage,
    RoomPropertyMessage,
    RoomQueueStatusMessage,
    RoomRatingMessage,
    RoomReadyMessage,
    RoomSettingsDataEventMessage,
    RoomSettingsErrorEventMessage,
    RoomSettingsSavedEventMessage,
    RoomSettingsSaveErrorEventMessage,
    RoomUseHabbiconMessage,
    RoomVisitsMessage,
    RoomVisualizationSettingsMessage,
    SanctionStatusEventMessage,
    ScrSendKickbackInfoMessage,
    ScrSendUserInfoMessage,
    SeasonalCalendarDailyOfferMessage,
    SelectInitialRoomMessage,
    SelfDonationResultMessage,
    SellablePetPalettesMessage,
    ShoutMessage,
    ShowEnforceRoomCategoryDialogMessage,
    ShowMysteryBoxWaitMessage,
    SilverBalanceMessage,
    SleepMessage,
    SlideObjectBundleMessage,
    SnowWarGameTokensMessage,
    SpecialRoomEffectMessage,
    TargetedOfferEventMessage,
    TargetedOfferNotFoundEventMessage,
    ThumbnailStatusMessage,
    TradeOpenFailedEventPaserMessage,
    TradeSilverFeeMessage,
    TradeSilverSetMessage,
    TradingAcceptEventMessage,
    TradingCloseEventMessage,
    TradingCompletedEventMessage,
    TradingConfirmationEventMessage,
    TradingItemListEventMessage,
    TradingNotOpenEventMessage,
    TradingOpenEventMessage,
    TradingOtherNotAllowedEventMessage,
    TradingYouAreNotAllowedEventMessage,
    TraxSongInfoMessage,
    UniqueMachineIdMessage,
    UnseenItemsEventMessage,
    UpdateMessage,
    UpgradeChestResultMessage,
    UseObjectMessage,
    UserChangeMessage,
    UserChatlogMessage,
    UserEventCatsMessage,
    UserFlatCatsMessage,
    UserGameAchievementsMessage,
    UserHabbiconsMessage,
    UserHabbiconStatusChangedMessage,
    UserNameChangedMessage,
    UserNftChatStylesMessage,
    UserObjectMessage,
    UserPurchasableChatStyleChangedMessage,
    UserPurchasableChatStylesMessage,
    UserRemoveMessage,
    UserRightsMessage,
    UsersMessage,
    UserSongDisksInventoryMessage,
    UserTypingMessage,
    UserUnbannedFromRoomEventMessage,
    UserUpdateMessage,
    VariableFxConfigsMessage,
    VariableFxConfigsRemovedMessage,
    VariableFxStatusMessage,
    VariableFxStatusRemovedMessage,
    VoucherRedeemErrorMessage,
    VoucherRedeemOkMessage,
    WardrobeMessage,
    WeeklyGameRewardMessage,
    WeeklyGameRewardWinnersMessage,
    WhisperMessage,
    WiredAllVariableHoldersMessage,
    WiredAllVariablesDiffsMessage,
    WiredAllVariablesHashMessage,
    WiredClickSettingsMessage,
    WiredClickUserResponseMessage,
    WiredContractContentsMessage,
    WiredContractUpdateResultMessage,
    WiredEnvironmentMessage,
    WiredErrorLogsMessage,
    WiredFurniActionEventMessage,
    WiredFurniAddonEventMessage,
    WiredFurniConditionEventMessage,
    WiredFurniSelectorEventMessage,
    WiredFurniTriggerEventMessage,
    WiredFurniVariableEventMessage,
    WiredMenuErrorMessage,
    WiredMovementsMessage,
    WiredOpenContractMessage,
    WiredPermissionsEventMessage,
    WiredRewardResultMessage,
    WiredRoomLogsMessage,
    WiredRoomSettingsMessage,
    WiredRoomStatsMessage,
    WiredSaveSuccessEventMessage,
    WiredSetUserPermanentVariableResultMessage,
    WiredTradeCancelledMessage,
    WiredTradeCompletedMessage,
    WiredTradeInitiateMessage,
    WiredTradeItemsUpdateMessage,
    WiredTradeTransactionNotificationMessage,
    WiredTransactionFailMessage,
    WiredTransactionLogDetailsMessage,
    WiredTransactionLogListMessage,
    WiredTransactionSuccessMessage,
    WiredUserPermanentVariablesMessage,
    WiredUserVariablesListMessage,
    WiredValidationErrorEventMessage,
    WiredVariablesForObjectMessage,
    WiredWebApiKeyResultMessage,
    YouAreControllerMessage,
    YouAreNotControllerMessage,
    YouAreNotSpectatorMessage,
    YouAreOwnerMessage,
    YouArePlayingGameMessage,
    YouAreSpectatorMessage,
    YoutubeControlVideoMessage,
    YoutubeDisplayPlaylistsMessage,
    YoutubeDisplayVideoMessage,
} from './incoming';
import { IncomingHeader } from './IncomingHeader';

export const GetIncomingPackets = () => {
    return {
        // Advertisement
        [IncomingHeader.InterstitialMessage]: InterstitialMessage,
        [IncomingHeader.RoomAdErrorMessage]: RoomAdErrorEventMessage,

        // Handshake
        [IncomingHeader.AuthenticationOKMessage]: AuthenticationOKMessage,
        [IncomingHeader.CompleteDiffieHandshakeMessage]: CompleteDiffieHandshakeMessage,
        [IncomingHeader.GenericErrorMessage]: GenericErrorMessage,
        [IncomingHeader.InitDiffieHandshakeMessage]: InitDiffieHandshakeMessage,
        [IncomingHeader.IsFirstLoginOfDayMessage]: IsFirstLoginOfDayMessage,
        [IncomingHeader.NoobnessLevelMessage]: NoobnessLevelMessage,
        [IncomingHeader.PingMessage]: PingMessage,
        [IncomingHeader.UniqueMachineIDMessage]: UniqueMachineIdMessage,
        [IncomingHeader.UserObjectMessage]: UserObjectMessage,
        [IncomingHeader.UserRightsMessage]: UserRightsMessage,

        // Inventory Achievements
        [IncomingHeader.AchievementMessage]: AchievementEventMessage,
        [IncomingHeader.AchievementsMessage]: AchievementsEventMessage,
        [IncomingHeader.AchievementsScoreMessage]: AchievementsScoreEventMessage,

        // Misc
        [IncomingHeader.PerkAllowancesMessage]: PerkAllowancesMessage,
        [IncomingHeader.AvailabilityStatusMessage]: AvailabilityStatusMessage,
        [IncomingHeader.InfoHotelClosedMessage]: InfoHotelClosedMessage,
        [IncomingHeader.InfoHotelClosingMessage]: InfoHotelClosingMessage,
        [IncomingHeader.LoginFailedHotelClosedMessage]: LoginFailedHotelClosedMessage,
        [IncomingHeader.MaintenanceStatusMessage]: MaintenanceStatusMessage,
        [IncomingHeader.ChangeUserNameResultMessage]: ChangeUserNameResultMessage,
        [IncomingHeader.UserNameChangedMessage]: UserNameChangedMessage,
        [IncomingHeader.UserNftChatStylesMessage]: UserNftChatStylesMessage,
        [IncomingHeader.UserPurchasableChatStylesMessage]: UserPurchasableChatStylesMessage,
        [IncomingHeader.UserPurchasableChatStyleChangedMessage]: UserPurchasableChatStyleChangedMessage,
        [IncomingHeader.CheckUserNameResultMessage]: CheckUserNameResultMessage,
        [IncomingHeader.FigureUpdateMessage]: FigureUpdateEventMessage,
        [IncomingHeader.WardrobeMessage]: WardrobeMessage,
        [IncomingHeader.CfhSanctionMessage]: CfhSanctionMessage,
        [IncomingHeader.CfhTopicsInitMessage]: CfhTopicsInitMessage,
        [IncomingHeader.SanctionStatusMessage]: SanctionStatusEventMessage,
        [IncomingHeader.CameraPublishStatusMessage]: CameraPublishStatusMessage,
        [IncomingHeader.CameraPurchaseOKMessage]: CameraPurchaseOKMessage,
        [IncomingHeader.CameraStorageUrlMessage]: CameraStorageUrlMessage,
        [IncomingHeader.CompetitionStatusMessage]: CompetitionStatusMessage,
        [IncomingHeader.InitCameraMessage]: InitCameraMessage,
        [IncomingHeader.ThumbnailStatusMessage]: ThumbnailStatusMessage,
        [IncomingHeader.CampaignCalendarDataMessage]: CampaignCalendarDataMessage,
        [IncomingHeader.CampaignCalendarDoorOpenedMessage]: CampaignCalendarDoorOpenedMessage,
        [IncomingHeader.BonusRareInfoMessage]: BonusRareInfoMessage,
        [IncomingHeader.BuildersClubFurniCountMessage]: BuildersClubFurniCountMessage,
        [IncomingHeader.BuildersClubSubscriptionStatusMessage]: BuildersClubSubscriptionStatusMessage,
        [IncomingHeader.BundleDiscountRulesetMessage]: BundleDiscountRulesetMessage,
        [IncomingHeader.CatalogIndexMessage]: CatalogIndexMessage,
        [IncomingHeader.CatalogPageMessage]: CatalogPageMessage,
        [IncomingHeader.CatalogPageWithEarliestExpiryMessage]: CatalogPageWithEarliestExpiryMessage,
        [IncomingHeader.CatalogPublishedMessage]: CatalogPublishedMessage,
        [IncomingHeader.ClaimProductResultMessage]: ClaimProductResultMessage,
        [IncomingHeader.ClubGiftInfoMessage]: ClubGiftInfoEventMessage,
        [IncomingHeader.ClubGiftSelectedMessage]: ClubGiftSelectedEventMessage,
        [IncomingHeader.GiftReceiverNotFoundMessage]: GiftReceiverNotFoundEventMessage,
        [IncomingHeader.GiftWrappingConfigurationMessage]: GiftWrappingConfigurationEventMessage,
        [IncomingHeader.HabboClubExtendOfferMessage]: HabboClubExtendOfferMessage,
        [IncomingHeader.HabboClubOffersMessage]: HabboClubOffersMessage,
        [IncomingHeader.UserHabbiconStatusChangedMessage]: UserHabbiconStatusChangedMessage,
        [IncomingHeader.UserHabbiconsMessage]: UserHabbiconsMessage,
        [IncomingHeader.HabbiconShopDataMessage]: HabbiconShopDataMessage,
        [IncomingHeader.HabbiconInfoMessage]: HabbiconInfoMessage,
        [IncomingHeader.HasClaimedProductResponseMessage]: HasClaimedProductResponseMessage,
        [IncomingHeader.LimitedEditionSoldOutMessage]: LimitedEditionSoldOutEventMessage,
        [IncomingHeader.LimitedOfferAppearingNextMessage]: LimitedOfferAppearingNextMessage,
        [IncomingHeader.LtdRaffleEnteredMessage]: LtdRaffleEnteredMessage,
        [IncomingHeader.LtdRaffleResultMessage]: LtdRaffleResultMessage,
        [IncomingHeader.NotEnoughBalanceMessage]: NotEnoughBalanceMessage,
        [IncomingHeader.ProductOfferMessage]: ProductOfferEventMessage,
        [IncomingHeader.PurchaseErrorMessage]: PurchaseErrorMessage,
        [IncomingHeader.PurchaseNotAllowedMessage]: PurchaseNotAllowedMessage,
        [IncomingHeader.PurchaseOKMessage]: PurchaseOKMessage,
        [IncomingHeader.RoomAdPurchaseInfoMessage]: RoomAdPurchaseInfoEventMessage,
        [IncomingHeader.SeasonalCalendarDailyOfferMessage]: SeasonalCalendarDailyOfferMessage,
        [IncomingHeader.SellablePetPalettesMessage]: SellablePetPalettesMessage,
        [IncomingHeader.SnowWarGameTokensMessage]: SnowWarGameTokensMessage,
        [IncomingHeader.TargetedOfferMessage]: TargetedOfferEventMessage,
        [IncomingHeader.TargetedOfferNotFoundMessage]: TargetedOfferNotFoundEventMessage,
        [IncomingHeader.VoucherRedeemErrorMessage]: VoucherRedeemErrorMessage,
        [IncomingHeader.VoucherRedeemOkMessage]: VoucherRedeemOkMessage,
        [IncomingHeader.CollectableMintableItemTypesMessage]: CollectableMintableItemTypesMessage,
        [IncomingHeader.CollectibleMintableItemResultMessage]: CollectibleMintableItemResultMessage,
        [IncomingHeader.CollectibleMintingEnabledMessage]: CollectibleMintingEnabledMessage,
        [IncomingHeader.CollectibleMintTokenCountMessage]: CollectibleMintTokenCountMessage,
        [IncomingHeader.CollectibleMintTokenOffersMessage]: CollectibleMintTokenOffersMessage,
        [IncomingHeader.CollectibleWalletAddressesMessage]: CollectibleWalletAddressesMessage,
        [IncomingHeader.EmeraldBalanceMessage]: EmeraldBalanceMessage,
        [IncomingHeader.NftBonusItemClaimResultMessage]: NftBonusItemClaimResultMessage,
        [IncomingHeader.NftCollectionsMessage]: NftCollectionsMessage,
        [IncomingHeader.NftCollectionsScoreMessage]: NftCollectionsScoreMessage,
        [IncomingHeader.NftRewardItemClaimResultMessage]: NftRewardItemClaimResultMessage,
        [IncomingHeader.NftTransferAssetsResultMessage]: NftTransferAssetsResultMessage,
        [IncomingHeader.NftTransferFeeMessage]: NftTransferFeeMessage,
        [IncomingHeader.NftClaimResultMessage]: NftClaimResultMessage,
        [IncomingHeader.NftClaimsMessage]: NftClaimsMessage,
        [IncomingHeader.NftStoreOffersMessage]: NftStoreOffersMessage,
        [IncomingHeader.NftStorePurchaseMessage]: NftStorePurchaseMessage,
        [IncomingHeader.RedeemNftLootBoxResultMessage]: RedeemNftLootBoxResultMessage,
        [IncomingHeader.RedeemNftLootBoxStateMessage]: RedeemNftLootBoxStateMessage,
        [IncomingHeader.SilverBalanceMessage]: SilverBalanceMessage,
        [IncomingHeader.AcceptFriendResultMessage]: AcceptFriendResultMessage,
        [IncomingHeader.ConsoleMessageHistoryMessage]: ConsoleMessageHistoryMessage,
        [IncomingHeader.FindFriendsProcessResultMessage]: FindFriendsProcessResultMessage,
        [IncomingHeader.FollowFriendFailedMessage]: FollowFriendFailedMessage,
        [IncomingHeader.FriendListFragmentMessage]: FriendListFragmentMessage,
        [IncomingHeader.FriendListUpdateMessage]: FriendListUpdateMessage,
        [IncomingHeader.FriendNotificationMessage]: FriendNotificationMessage,
        [IncomingHeader.FriendRequestsMessage]: FriendRequestsMessage,
        [IncomingHeader.HabboSearchResultMessage]: HabboSearchResultMessage,
        [IncomingHeader.InstantMessageErrorMessage]: InstantMessageErrorMessage,
        [IncomingHeader.MessengerErrorMessage]: MessengerErrorMessage,
        [IncomingHeader.MessengerInitMessage]: MessengerInitMessage,
        [IncomingHeader.MiniMailNewMessage]: MiniMailNewMessage,
        [IncomingHeader.MiniMailUnreadCountMessage]: MiniMailUnreadCountMessage,
        [IncomingHeader.NewConsoleMessage]: NewConsoleMessageMessage,
        [IncomingHeader.NewFriendRequestMessage]: NewFriendRequestMessage,
        [IncomingHeader.RoomInviteErrorMessage]: RoomInviteErrorMessage,
        [IncomingHeader.RoomInviteMessage]: RoomInviteMessage,
        [IncomingHeader.AvatarEffectActivatedMessage]: AvatarEffectActivatedMessage,
        [IncomingHeader.AvatarEffectAddedMessage]: AvatarEffectAddedMessage,
        [IncomingHeader.AvatarEffectExpiredMessage]: AvatarEffectExpiredMessage,
        [IncomingHeader.AvatarEffectSelectedMessage]: AvatarEffectSelectedMessage,
        [IncomingHeader.AvatarEffectsMessage]: AvatarEffectsMessage,
        [IncomingHeader.BadgePointLimitsMessage]: BadgePointLimitsEventMessage,
        [IncomingHeader.BadgeReceivedMessage]: BadgeReceivedEventMessage,
        [IncomingHeader.BadgesMessage]: BadgesEventMessage,
        [IncomingHeader.IsBadgeRequestFulfilledMessage]: IsBadgeRequestFulfilledEventMessage,
        [IncomingHeader.BotAddedToInventoryMessage]: BotAddedToInventoryEventMessage,
        [IncomingHeader.BotInventoryMessage]: BotInventoryEventMessage,
        [IncomingHeader.BotRemovedFromInventoryMessage]: BotRemovedFromInventoryEventMessage,
        [IncomingHeader.FigureSetIdsMessage]: FigureSetIdsEventMessage,
        [IncomingHeader.FurniListAddOrUpdateMessage]: FurniListAddOrUpdateEventMessage,
        [IncomingHeader.FurniListMessage]: FurniListEventMessage,
        [IncomingHeader.FurniListInvalidateMessage]: FurniListInvalidateEventMessage,
        [IncomingHeader.FurniListRemoveMessage]: FurniListRemoveEventMessage,
        [IncomingHeader.PostItPlacedMessage]: PostItPlacedEventMessage,
        [IncomingHeader.ConfirmBreedingRequestMessage]: ConfirmBreedingRequestEventMessage,
        [IncomingHeader.ConfirmBreedingResultMessage]: ConfirmBreedingResultEventMessage,
        [IncomingHeader.GoToBreedingNestFailureMessage]: GoToBreedingNestFailureEventMessage,
        [IncomingHeader.NestBreedingSuccessMessage]: NestBreedingSuccessEventMessage,
        [IncomingHeader.PetAddedToInventoryMessage]: PetAddedToInventoryEventMessage,
        [IncomingHeader.PetBreedingMessage]: PetBreedingEventMessage,
        [IncomingHeader.PetInventoryMessage]: PetInventoryEventMessage,
        [IncomingHeader.PetReceivedMessage]: PetReceivedMessage,
        [IncomingHeader.PetRemovedFromInventoryMessage]: PetRemovedFromInventoryEventMessage,
        [IncomingHeader.CreditBalanceMessage]: CreditBalanceEventMessage,
        [IncomingHeader.TradeOpenFailedMessage]: TradeOpenFailedEventPaserMessage,
        [IncomingHeader.TradeSilverFeeMessage]: TradeSilverFeeMessage,
        [IncomingHeader.TradeSilverSetMessage]: TradeSilverSetMessage,
        [IncomingHeader.TradingAcceptMessage]: TradingAcceptEventMessage,
        [IncomingHeader.TradingCloseMessage]: TradingCloseEventMessage,
        [IncomingHeader.TradingCompletedMessage]: TradingCompletedEventMessage,
        [IncomingHeader.TradingConfirmationMessage]: TradingConfirmationEventMessage,
        [IncomingHeader.TradingItemListMessage]: TradingItemListEventMessage,
        [IncomingHeader.TradingNotOpenMessage]: TradingNotOpenEventMessage,
        [IncomingHeader.TradingOpenMessage]: TradingOpenEventMessage,
        [IncomingHeader.TradingOtherNotAllowedMessage]: TradingOtherNotAllowedEventMessage,
        [IncomingHeader.TradingYouAreNotAllowedMessage]: TradingYouAreNotAllowedEventMessage,
        [IncomingHeader.CancelMysteryBoxWaitMessage]: CancelMysteryBoxWaitMessage,
        [IncomingHeader.GotMysteryBoxPrizeMessage]: GotMysteryBoxPrizeMessage,
        [IncomingHeader.MysteryBoxKeysMessage]: MysteryBoxKeysMessage,
        [IncomingHeader.ShowMysteryBoxWaitMessage]: ShowMysteryBoxWaitMessage,
        [IncomingHeader.CanCreateRoomEventMessage]: CanCreateRoomEventMessage,
        [IncomingHeader.CanCreateRoomMessage]: CanCreateRoomMessage,
        [IncomingHeader.CategoriesWithVisitorCountMessage]: CategoriesWithVisitorCountMessage,
        [IncomingHeader.CompetitionRoomsDataMessage]: CompetitionRoomsDataMessage,
        [IncomingHeader.ConvertedRoomIdMessage]: ConvertedRoomIdMessage,
        [IncomingHeader.DoorbellMessage]: DoorbellMessage,
        [IncomingHeader.FavouriteChangedMessage]: FavouriteChangedMessage,
        [IncomingHeader.FavouritesMessage]: FavouritesMessage,
        [IncomingHeader.FlatAccessDeniedMessage]: FlatAccessDeniedMessage,
        [IncomingHeader.FlatCreatedMessage]: FlatCreatedMessage,
        [IncomingHeader.GetGuestRoomResultMessage]: GetGuestRoomResultMessage,
        [IncomingHeader.GuestRoomSearchResultMessage]: GuestRoomSearchResultMessage,
        [IncomingHeader.NavigatorSettingsMessage]: NavigatorSettingsMessage,
        [IncomingHeader.OfficialRoomsMessage]: OfficialRoomsMessage,
        [IncomingHeader.PopularRoomTagsResultMessage]: PopularRoomTagsResultMessage,
        [IncomingHeader.RoomEventCancelMessage]: RoomEventCancelMessage,
        [IncomingHeader.RoomEventMessage]: RoomEventMessage,
        [IncomingHeader.RoomInfoUpdatedMessage]: RoomInfoUpdatedMessage,
        [IncomingHeader.RoomRatingMessage]: RoomRatingMessage,
        [IncomingHeader.UserEventCatsMessage]: UserEventCatsMessage,
        [IncomingHeader.UserFlatCatsMessage]: UserFlatCatsMessage,
        [IncomingHeader.NavigatorCollapsedCategoriesMessage]: NavigatorCollapsedCategoriesMessage,
        [IncomingHeader.NavigatorLiftedRoomsMessage]: NavigatorLiftedRoomsMessage,
        [IncomingHeader.NavigatorMetaDataMessage]: NavigatorMetadataMessage,
        [IncomingHeader.NavigatorSavedSearchesMessage]: NavigatorSavedSearchesMessage,
        [IncomingHeader.NavigatorSearchResultBlocksMessage]: NavigatorSearchResultBlocksMessage,
        [IncomingHeader.NewNavigatorPreferencesMessage]: NewNavigatorPreferencesMessage,
        [IncomingHeader.ActivityPointsMessage]: ActivityPointsMessage,
        [IncomingHeader.ClubGiftNotificationMessage]: ClubGiftNotificationEventMessage,
        [IncomingHeader.ElementPointerMessage]: ElementPointerMessage,
        [IncomingHeader.HabboAchievementNotificationMessage]: HabboAchievementNotificationMessage,
        [IncomingHeader.HabboActivityPointNotificationMessage]: HabboActivityPointNotificationMessage,
        [IncomingHeader.HabboBroadcastMessage]: HabboBroadcastMessage,
        [IncomingHeader.InfoFeedEnableMessage]: InfoFeedEnableMessage,
        [IncomingHeader.MOTDNotificationMessage]: MOTDNotificationEventMessage,
        [IncomingHeader.NotificationDialogMessage]: NotificationDialogMessage,
        [IncomingHeader.OfferRewardDeliveredMessage]: OfferRewardDeliveredMessage,
        [IncomingHeader.PetLevelNotificationMessage]: PetLevelNotificationEventMessage,
        [IncomingHeader.RestoreClientMessage]: RestoreClientMessage,
        [IncomingHeader.UnseenItemsMessage]: UnseenItemsEventMessage,
        [IncomingHeader.AccountPreferencesMessage]: AccountPreferencesEventMessage,
        [IncomingHeader.BotCommandConfigurationMessage]: BotCommandConfigurationMessage,
        [IncomingHeader.BotErrorMessage]: BotErrorMessage,
        [IncomingHeader.BotForceOpenContextMenuMessage]: BotForceOpenContextMenuMessage,
        [IncomingHeader.BotSkillListUpdateMessage]: BotSkillListUpdateMessage,
        [IncomingHeader.ChatMessage]: ChatMessage,
        [IncomingHeader.WhisperMessage]: WhisperMessage,
        [IncomingHeader.ShoutMessage]: ShoutMessage,
        [IncomingHeader.FloodControlMessage]: FloodControlMessage,
        [IncomingHeader.RemainingMutePeriodMessage]: RemainingMutePeriodMessage,
        [IncomingHeader.RoomChatSettingsMessage]: RoomChatSettingsMessage,
        [IncomingHeader.RoomFilterSettingsMessage]: RoomFilterSettingsMessage,
        [IncomingHeader.UserTypingMessage]: UserTypingMessage,
        [IncomingHeader.HandItemReceivedMessage]: HandItemReceivedMessage,
        [IncomingHeader.RespectNotificationMessage]: RespectNotificationMessage,
        [IncomingHeader.BuildersClubPlacementWarningMessage]: BuildersClubPlacementWarningMessage,
        [IncomingHeader.FavoriteMembershipUpdateMessage]: FavoriteMembershipUpdateMessage,
        [IncomingHeader.FloorHeightMapMessage]: FloorHeightMapMessage,
        [IncomingHeader.FurnitureAliasesMessage]: FurnitureAliasesMessage,
        [IncomingHeader.HeightMapMessage]: HeightMapMessage,
        [IncomingHeader.HeightMapUpdateMessage]: HeightMapUpdateMessage,
        [IncomingHeader.ItemAddMessage]: ItemAddMessage,
        [IncomingHeader.ItemDataUpdateMessage]: ItemDataUpdateMessage,
        [IncomingHeader.ItemRemoveMessage]: ItemRemoveMessage,
        [IncomingHeader.ItemsMessage]: ItemsMessage,
        [IncomingHeader.ItemsStateUpdateMessage]: ItemsStateUpdateMessage,
        [IncomingHeader.ItemStateUpdateMessage]: ItemStateUpdateMessage,
        [IncomingHeader.ItemUpdateMessage]: ItemUpdateMessage,
        [IncomingHeader.ObjectAddMessage]: ObjectAddMessage,
        [IncomingHeader.ObjectDataUpdateMessage]: ObjectDataUpdateMessage,
        [IncomingHeader.ObjectRemoveConfirmMessage]: ObjectRemoveConfirmMessage,
        [IncomingHeader.ObjectRemoveMessage]: ObjectRemoveMessage,
        [IncomingHeader.ObjectRemoveMultipleMessage]: ObjectRemoveMultipleMessage,
        [IncomingHeader.ObjectsDataUpdateMessage]: ObjectsDataUpdateMessage,
        [IncomingHeader.ObjectsMessage]: ObjectsMessage,
        [IncomingHeader.ObjectUpdateMessage]: ObjectUpdateMessage,
        [IncomingHeader.RoomEntryInfoMessage]: RoomEntryInfoMessage,
        [IncomingHeader.RoomUseHabbiconMessage]: RoomUseHabbiconMessage,
        [IncomingHeader.RoomPropertyMessage]: RoomPropertyMessage,
        [IncomingHeader.RoomVisualizationSettingsMessage]: RoomVisualizationSettingsMessage,
        [IncomingHeader.SlideObjectBundleMessage]: SlideObjectBundleMessage,
        [IncomingHeader.SpecialRoomEffectMessage]: SpecialRoomEffectMessage,
        [IncomingHeader.UserChangeMessage]: UserChangeMessage,
        [IncomingHeader.UserRemoveMessage]: UserRemoveMessage,
        [IncomingHeader.UsersMessage]: UsersMessage,
        [IncomingHeader.UserUpdateMessage]: UserUpdateMessage,
        [IncomingHeader.WiredMovementsMessage]: WiredMovementsMessage,
        [IncomingHeader.AreaHideMessage]: AreaHideMessage,
        [IncomingHeader.CustomUserNotificationMessage]: CustomUserNotificationMessage,
        [IncomingHeader.DiceValueMessage]: DiceValueMessage,
        [IncomingHeader.FurniRentOrBuyoutOfferMessage]: FurniRentOrBuyoutOfferMessage,
        [IncomingHeader.GuildFurniContextMenuInfoMessage]: GuildFurniContextMenuInfoMessage,
        [IncomingHeader.OneWayDoorStatusMessage]: OneWayDoorStatusMessage,
        [IncomingHeader.OpenPetPackageRequestedMessage]: OpenPetPackageRequestedMessage,
        [IncomingHeader.OpenPetPackageResultMessage]: OpenPetPackageResultMessage,
        [IncomingHeader.PresentOpenedMessage]: PresentOpenedMessage,
        [IncomingHeader.RentableSpaceRentFailedMessage]: RentableSpaceRentFailedMessage,
        [IncomingHeader.RentableSpaceRentOkMessage]: RentableSpaceRentOkMessage,
        [IncomingHeader.RentableSpaceStatusMessage]: RentableSpaceStatusMessage,
        [IncomingHeader.RequestSpamWallPostItMessage]: RequestSpamWallPostItMessage,
        [IncomingHeader.RoomDimmerPresetsMessage]: RoomDimmerPresetsMessage,
        [IncomingHeader.RoomMessageNotificationMessage]: RoomMessageNotificationMessage,
        [IncomingHeader.YoutubeControlVideoMessage]: YoutubeControlVideoMessage,
        [IncomingHeader.YoutubeDisplayPlaylistsMessage]: YoutubeDisplayPlaylistsMessage,
        [IncomingHeader.YoutubeDisplayVideoMessage]: YoutubeDisplayVideoMessage,
        [IncomingHeader.RoomEntryTileMessage]: RoomEntryTileMessage,
        [IncomingHeader.RoomOccupiedTilesMessage]: RoomOccupiedTilesMessage,
        [IncomingHeader.YouAreControllerMessage]: YouAreControllerMessage,
        [IncomingHeader.YouAreNotControllerMessage]: YouAreNotControllerMessage,
        [IncomingHeader.YouAreOwnerMessage]: YouAreOwnerMessage,
        [IncomingHeader.PetBreedingResultMessage]: PetBreedingResultEventMessage,
        [IncomingHeader.PetCommandsMessage]: PetCommandsMessage,
        [IncomingHeader.PetExperienceMessage]: PetExperienceMessage,
        [IncomingHeader.PetFigureUpdateMessage]: PetFigureUpdateMessage,
        [IncomingHeader.PetInfoMessage]: PetInfoMessage,
        [IncomingHeader.PetLevelUpdateMessage]: PetLevelUpdateMessage,
        [IncomingHeader.PetPlacingErrorMessage]: PetPlacingErrorMessage,
        [IncomingHeader.PetRespectFailedMessage]: PetRespectFailedMessage,
        [IncomingHeader.PetRespectNotificationMessage]: PetRespectNotificationEventMessage,
        [IncomingHeader.PetSupplementedNotificationMessage]: PetSupplementedNotificationEventMessage,
        [IncomingHeader.PetStatusUpdateMessage]: PetStatusUpdateMessage,
        [IncomingHeader.CantConnectMessage]: CantConnectMessage,
        [IncomingHeader.CloseConnectionMessage]: CloseConnectionMessage,
        [IncomingHeader.ConfigurationItemStatesMessage]: ConfigurationItemStatesMessage,
        [IncomingHeader.FlatAccessibleMessage]: FlatAccessibleMessage,
        [IncomingHeader.GamePlayerValueMessage]: GamePlayerValueMessage,
        [IncomingHeader.OpenConnectionMessage]: OpenConnectionMessage,
        [IncomingHeader.RoomForwardMessage]: RoomForwardMessage,
        [IncomingHeader.RoomQueueStatusMessage]: RoomQueueStatusMessage,
        [IncomingHeader.RoomReadyMessage]: RoomReadyMessage,
        [IncomingHeader.YouAreNotSpectatorMessage]: YouAreNotSpectatorMessage,
        [IncomingHeader.YouArePlayingGameMessage]: YouArePlayingGameMessage,
        [IncomingHeader.YouAreSpectatorMessage]: YouAreSpectatorMessage,
        [IncomingHeader.OpenMessage]: OpenEventMessage,
        [IncomingHeader.VariableFxConfigsMessage]: VariableFxConfigsMessage,
        [IncomingHeader.VariableFxConfigsRemovedMessage]: VariableFxConfigsRemovedMessage,
        [IncomingHeader.VariableFxStatusMessage]: VariableFxStatusMessage,
        [IncomingHeader.VariableFxStatusRemovedMessage]: VariableFxStatusRemovedMessage,
        [IncomingHeader.WiredFurniActionMessage]: WiredFurniActionEventMessage,
        [IncomingHeader.WiredFurniAddonMessage]: WiredFurniAddonEventMessage,
        [IncomingHeader.WiredFurniConditionMessage]: WiredFurniConditionEventMessage,
        [IncomingHeader.WiredFurniSelectorMessage]: WiredFurniSelectorEventMessage,
        [IncomingHeader.WiredFurniTriggerMessage]: WiredFurniTriggerEventMessage,
        [IncomingHeader.WiredFurniVariableMessage]: WiredFurniVariableEventMessage,
        [IncomingHeader.WiredRewardResultMessage]: WiredRewardResultMessage,
        [IncomingHeader.WiredSaveSuccessMessage]: WiredSaveSuccessEventMessage,
        [IncomingHeader.WiredValidationErrorMessage]: WiredValidationErrorEventMessage,
        [IncomingHeader.AccountSafetyLockStatusChangeMessage]: AccountSafetyLockStatusChangeMessage,
        [IncomingHeader.ApproveNameMessage]: ApproveNameMessage,
        [IncomingHeader.ChangeEmailResultMessage]: ChangeEmailResultEventMessage,
        [IncomingHeader.EmailStatusResultMessage]: EmailStatusResultEventMessage,
        [IncomingHeader.ExtendedProfileChangedMessage]: ExtendedProfileChangedMessage,
        [IncomingHeader.ScrSendUserInfoMessage]: ScrSendUserInfoMessage,
        [IncomingHeader.ScrSendKickbackInfoMessage]: ScrSendKickbackInfoMessage,
        [IncomingHeader.IncomeRewardClaimResponseMessage]: IncomeRewardClaimResponseMessage,
        [IncomingHeader.IncomeRewardNotificationMessage]: IncomeRewardNotificationMessage,
        [IncomingHeader.IncomeRewardStatusMessage]: IncomeRewardStatusMessage,

        // Room Action
        [IncomingHeader.AvatarEffectMessage]: AvatarEffectMessage,
        [IncomingHeader.CarryObjectMessage]: CarryObjectMessage,
        [IncomingHeader.DanceMessage]: DanceMessage,
        [IncomingHeader.ExpressionMessage]: ExpressionMessage,
        [IncomingHeader.SleepMessage]: SleepMessage,
        [IncomingHeader.UseObjectMessage]: UseObjectMessage,

        // Registered late: each had a listener and a parser but no entry here, so the listener was
        // refused and the packet dropped.
        [IncomingHeader.QuestionMessage]: QuestionEventMessage,
        [IncomingHeader.QuestionAnsweredMessage]: QuestionAnsweredEventMessage,
        [IncomingHeader.QuestionFinishedMessage]: QuestionFinishedEventMessage,
        [IncomingHeader.RecyclerFinishedMessage]: RecyclerFinishedMessage,
        [IncomingHeader.RecyclerPrizesMessage]: RecyclerPrizesMessage,
        [IncomingHeader.RecyclerStatusMessage]: RecyclerStatusMessage,
        [IncomingHeader.RoomSettingsDataMessage]: RoomSettingsDataEventMessage,
        [IncomingHeader.RoomSettingsErrorMessage]: RoomSettingsErrorEventMessage,
        [IncomingHeader.RoomSettingsSavedMessage]: RoomSettingsSavedEventMessage,
        [IncomingHeader.RoomSettingsSaveErrorMessage]: RoomSettingsSaveErrorEventMessage,
        [IncomingHeader.FlatControllersMessage]: FlatControllersEventMessage,
        [IncomingHeader.FlatControllerAddedMessage]: FlatControllerAddedEventMessage,
        [IncomingHeader.FlatControllerRemovedMessage]: FlatControllerRemovedEventMessage,
        [IncomingHeader.BannedUsersFromRoomMessage]: BannedUsersFromRoomEventMessage,
        [IncomingHeader.UserUnbannedFromRoomMessage]: UserUnbannedFromRoomEventMessage,
        [IncomingHeader.CraftableProductsMessage]: CraftableProductsMessage,
        [IncomingHeader.CraftingRecipeMessage]: CraftingRecipeMessage,
        [IncomingHeader.CraftingRecipesAvailableMessage]: CraftingRecipesAvailableMessage,
        [IncomingHeader.CraftingResultMessage]: CraftingResultMessage,
        [IncomingHeader.FriendFurniCancelLockMessage]: FriendFurniCancelLockMessage,
        [IncomingHeader.FriendFurniOtherLockConfirmedMessage]: FriendFurniOtherLockConfirmedMessage,
        [IncomingHeader.FriendFurniStartConfirmationMessage]: FriendFurniStartConfirmationMessage,
        [IncomingHeader.JukeboxSongDisksMessage]: JukeboxSongDisksMessage,
        [IncomingHeader.NowPlayingMessage]: NowPlayingMessage,
        [IncomingHeader.OfficialSongIdMessage]: OfficialSongIdMessage,
        [IncomingHeader.PlayListMessage]: PlayListMessage,
        [IncomingHeader.TraxSongInfoMessage]: TraxSongInfoMessage,
        [IncomingHeader.UserSongDisksInventoryMessage]: UserSongDisksInventoryMessage,

        // Poll
        [IncomingHeader.PollContentsMessage]: PollContentsEventMessage,
        [IncomingHeader.PollErrorMessage]: PollErrorEventMessage,
        [IncomingHeader.PollOfferMessage]: PollOfferEventMessage,

        // Tracking
        [IncomingHeader.LatencyPingResponseMessage]: LatencyPingResponseMessage,

        // Userdefinedroomevents Wiredmenu
        [IncomingHeader.WiredPermissionsMessage]: WiredPermissionsEventMessage,
        [IncomingHeader.ChestPreferencesUpdateSuccessMessage]: ChestPreferencesUpdateSuccessMessage,
        [IncomingHeader.CoinsChestContentsMessage]: CoinsChestContentsMessage,
        [IncomingHeader.ItemsChestContentsChunkMessage]: ItemsChestContentsChunkMessage,
        [IncomingHeader.ItemsChestContentsUpdatedMessage]: ItemsChestContentsUpdatedMessage,
        [IncomingHeader.OpenChestMessage]: OpenChestMessage,
        [IncomingHeader.UpgradeChestResultMessage]: UpgradeChestResultMessage,

        // Infostand and avatar menu
        [IncomingHeader.HabboUserBadgesMessage]: HabboUserBadgesMessage,
        [IncomingHeader.RelationshipStatusInfoMessage]: RelationshipStatusInfoEventMessage,
        [IncomingHeader.IgnoredUsersMessage]: IgnoredUsersMessage,
        [IncomingHeader.IgnoreResultMessage]: IgnoreResultMessage,
        [IncomingHeader.HabboGroupBadgesMessage]: HabboGroupBadgesMessage,
        [IncomingHeader.HabboGroupDetailsMessage]: HabboGroupDetailsMessage,
        [IncomingHeader.GuildMembershipsMessage]: GuildMembershipsMessage,
        [IncomingHeader.BlockListMessage]: BlockListMessage,
        [IncomingHeader.BlockUserUpdateMessage]: BlockUserUpdateMessage,

        // Renamed by the protocol: these carried their pre-rename class names and were never registered.
        [IncomingHeader.CfhChatlogMessage]: CfhChatlogMessage,
        [IncomingHeader.CitizenshipVipOfferPromoEnabledMessage]: CitizenshipVipOfferPromoEnabledMessage,
        [IncomingHeader.CommunityVoteReceivedMessage]: CommunityVoteReceivedMessage,
        [IncomingHeader.DisconnectReasonMessage]: DisconnectReasonMessage,
        [IncomingHeader.ErrorReportMessage]: ErrorReportMessage,
        [IncomingHeader.Game2AccountGameStatusMessage]: Game2AccountGameStatusMessage,
        [IncomingHeader.Game2GameCancelledMessage]: Game2GameCancelledMessage,
        [IncomingHeader.Game2GameDirectoryStatusMessage]: Game2GameDirectoryStatusMessage,
        [IncomingHeader.Game2GameNotFoundMessage]: Game2GameNotFoundMessage,
        [IncomingHeader.Game2InArenaQueueMessage]: Game2InArenaQueueMessage,
        [IncomingHeader.Game2JoiningGameFailedMessage]: Game2JoiningGameFailedMessage,
        [IncomingHeader.Game2StartCounterMessage]: Game2StartCounterMessage,
        [IncomingHeader.Game2StartingGameFailedMessage]: Game2StartingGameFailedMessage,
        [IncomingHeader.Game2StopCounterMessage]: Game2StopCounterMessage,
        [IncomingHeader.Game2UserBlockedMessage]: Game2UserBlockedMessage,
        [IncomingHeader.Game2UserLeftGameMessage]: Game2UserLeftGameMessage,
        [IncomingHeader.GuideSessionMessage]: GuideSessionMessage,
        [IncomingHeader.IdentityAccountsMessage]: IdentityAccountsMessage,
        [IncomingHeader.MarketplaceBuyOfferResultMessage]: MarketplaceBuyOfferResultMessage,
        [IncomingHeader.MarketplaceCancelAllOffersResultMessage]: MarketplaceCancelAllOffersResultMessage,
        [IncomingHeader.MarketplaceCancelOfferResultMessage]: MarketplaceCancelOfferResultMessage,
        [IncomingHeader.MarketplaceCanMakeOfferResultMessage]: MarketplaceCanMakeOfferResultMessage,
        [IncomingHeader.MarketplaceClearOwnHistoryResultMessage]: MarketplaceClearOwnHistoryResultMessage,
        [IncomingHeader.MarketplaceConfigurationMessage]: MarketplaceConfigurationMessage,
        [IncomingHeader.MarketplaceItemStatsMessage]: MarketplaceItemStatsMessage,
        [IncomingHeader.MarketplaceMakeOfferResultMessage]: MarketplaceMakeOfferResultMessage,
        [IncomingHeader.MarketPlaceOffersMessage]: MarketPlaceOffersMessage,
        [IncomingHeader.MarketPlaceOwnOffersMessage]: MarketPlaceOwnOffersMessage,
        [IncomingHeader.ModeratorCautionMessage]: ModeratorCautionMessage,
        [IncomingHeader.ModeratorRoomInfoMessage]: ModeratorRoomInfoMessage,
        [IncomingHeader.ModeratorToolPreferencesMessage]: ModeratorToolPreferencesMessage,
        [IncomingHeader.ModeratorUserInfoMessage]: ModeratorUserInfoMessage,
        [IncomingHeader.MuteAllInRoomMessage]: MuteAllInRoomMessage,
        [IncomingHeader.NewUserExperienceGiftOfferMessage]: NewUserExperienceGiftOfferMessage,
        [IncomingHeader.NewUserExperienceNotCompleteMessage]: NewUserExperienceNotCompleteMessage,
        [IncomingHeader.NoSuchFlatMessage]: NoSuchFlatMessage,
        [IncomingHeader.PostMessage]: PostMessage,
        [IncomingHeader.RoomChatlogMessage]: RoomChatlogMessage,
        [IncomingHeader.RoomVisitsMessage]: RoomVisitsMessage,
        [IncomingHeader.SelectInitialRoomMessage]: SelectInitialRoomMessage,
        [IncomingHeader.ShowEnforceRoomCategoryDialogMessage]: ShowEnforceRoomCategoryDialogMessage,
        [IncomingHeader.UpdateMessage]: UpdateMessage,
        [IncomingHeader.UserChatlogMessage]: UserChatlogMessage,
        [IncomingHeader.UserGameAchievementsMessage]: UserGameAchievementsMessage,
        [IncomingHeader.WeeklyGameRewardMessage]: WeeklyGameRewardMessage,
        [IncomingHeader.WeeklyGameRewardWinnersMessage]: WeeklyGameRewardWinnersMessage,
        [IncomingHeader.WiredAllVariableHoldersMessage]: WiredAllVariableHoldersMessage,
        [IncomingHeader.WiredAllVariablesDiffsMessage]: WiredAllVariablesDiffsMessage,
        [IncomingHeader.WiredAllVariablesHashMessage]: WiredAllVariablesHashMessage,
        [IncomingHeader.WiredErrorLogsMessage]: WiredErrorLogsMessage,
        [IncomingHeader.WiredMenuErrorMessage]: WiredMenuErrorMessage,
        [IncomingHeader.WiredRoomSettingsMessage]: WiredRoomSettingsMessage,
        [IncomingHeader.WiredRoomStatsMessage]: WiredRoomStatsMessage,
        [IncomingHeader.WiredVariablesForObjectMessage]: WiredVariablesForObjectMessage,
        [IncomingHeader.SelfDonationResultMessage]: SelfDonationResultMessage,
        [IncomingHeader.WiredClickSettingsMessage]: WiredClickSettingsMessage,
        [IncomingHeader.WiredClickUserResponseMessage]: WiredClickUserResponseMessage,
        [IncomingHeader.WiredContractContentsMessage]: WiredContractContentsMessage,
        [IncomingHeader.WiredContractUpdateResultMessage]: WiredContractUpdateResultMessage,
        [IncomingHeader.WiredEnvironmentMessage]: WiredEnvironmentMessage,
        [IncomingHeader.WiredOpenContractMessage]: WiredOpenContractMessage,
        [IncomingHeader.WiredRoomLogsMessage]: WiredRoomLogsMessage,
        [IncomingHeader.WiredSetUserPermanentVariableResultMessage]: WiredSetUserPermanentVariableResultMessage,
        [IncomingHeader.WiredTradeCancelledMessage]: WiredTradeCancelledMessage,
        [IncomingHeader.WiredTradeCompletedMessage]: WiredTradeCompletedMessage,
        [IncomingHeader.WiredTradeInitiateMessage]: WiredTradeInitiateMessage,
        [IncomingHeader.WiredTradeItemsUpdateMessage]: WiredTradeItemsUpdateMessage,
        [IncomingHeader.WiredTradeTransactionNotificationMessage]: WiredTradeTransactionNotificationMessage,
        [IncomingHeader.WiredTransactionFailMessage]: WiredTransactionFailMessage,
        [IncomingHeader.WiredTransactionLogDetailsMessage]: WiredTransactionLogDetailsMessage,
        [IncomingHeader.WiredTransactionLogListMessage]: WiredTransactionLogListMessage,
        [IncomingHeader.WiredTransactionSuccessMessage]: WiredTransactionSuccessMessage,
        [IncomingHeader.WiredUserPermanentVariablesMessage]: WiredUserPermanentVariablesMessage,
        [IncomingHeader.WiredUserVariablesListMessage]: WiredUserVariablesListMessage,
        [IncomingHeader.WiredWebApiKeyResultMessage]: WiredWebApiKeyResultMessage,
    } as Record<number, IncomingPacketConstructor>;
};
