export * from './IAvatarCanvas';
export * from './IAvatarStructure';
export * from './IFigurePart';
export * from './IFigurePartSet';
export * from './IFigureSetData';
export * from './IPalette';
export * from './IPartColor';
export * from './ISetType';
export * from './IStructureData';
