/** Generates the public barrels for React stores, hooks, handlers and supporting modules. */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const sourceRoot = resolve('src');
const barrelRoots = [ 'context', 'hooks', 'handlers', 'commands', 'components', 'utils', 'chat' ];
const header = '// Generated by scripts/generate-barrels.ts - run it instead of editing by hand.\n';
const check = process.argv.includes('--check');
const changes: string[] = [];

const compareNames = (a: string, b: string) => a.toLowerCase().localeCompare(b.toLowerCase()) || a.localeCompare(b);

const visit = (directory: string, root: string) => {
    const entries = readdirSync(directory, { withFileTypes: true });
    const candidates = entries
        .filter(entry => entry.isDirectory() || ((entry.isFile()) && /\.tsx?$/.test(entry.name) && !entry.name.endsWith('.d.ts') && (entry.name !== 'index.ts')))
        .map(entry => ({ entry, name: entry.isDirectory() ? entry.name : entry.name.replace(/\.tsx?$/, '') }))
        .sort((a, b) => compareNames(a.name, b.name));
    const output = candidates.length
        ? header + candidates.map(({ name }) => `export * from './${name}';\n`).join('')
        : '';
    const indexPath = join(directory, 'index.ts');
    const existing = entries.some(entry => entry.isFile() && entry.name === 'index.ts');
    const isBarrelRoot = directory === join(sourceRoot, root);

    if (output && (existing || !isBarrelRoot)) {
        if (!existing || readFileSync(indexPath, 'utf8') !== output) {
            changes.push(relative(sourceRoot, indexPath));
            if (!check) writeFileSync(indexPath, output);
        }
    }

    for (const entry of entries) {
        if (entry.isDirectory()) visit(join(directory, entry.name), root);
    }
};

for (const root of barrelRoots) visit(join(sourceRoot, root), root);

if (changes.length) {
    if (check) {
        console.error(`Stale generated barrels:\n${changes.join('\n')}`);
        process.exitCode = 1;
    } else {
        console.log(`Generated ${changes.length} barrel(s).`);
    }
} else {
    console.log('Barrels are up to date.');
}
