export enum AvatarFigurePartType {
    None = '',
    Standard = 'std',
    Body = 'bd',
    BodySwim = 'bds',
    Shoes = 'sh',
    Legs = 'lg',
    Chest = 'ch',
    WaistAccessory = 'wa',
    ChestAccessory = 'ca',
    Head = 'hd',
    Hair = 'hr',
    FaceAccessory = 'fa',
    EyeAccessory = 'ea',
    HeadAccessory = 'ha',
    HeadAccessoryExtra = 'he',
    CoatChest = 'cc',
    ChestPrint = 'cp',
    LeftHandItem = 'li',
    LeftHand = 'lh',
    LeftHandSwim = 'lhs',
    LeftSleeve = 'ls',
    RightHand = 'rh',
    RightHandSwim = 'rhs',
    RightSleeve = 'rs',
    Face = 'fc',
    Eyes = 'ey',
    HairBig = 'hrb',
    RightHandItem = 'ri',
    LeftCoatSleeve = 'lc',
    RightCoatSleeve = 'rc',
    Ss = 'ss'
}

const DEFAULT_FRAME = 0;

const FIGURE_SETS: string[] = [
    AvatarFigurePartType.Shoes,
    AvatarFigurePartType.Legs,
    AvatarFigurePartType.Chest,
    AvatarFigurePartType.WaistAccessory,
    AvatarFigurePartType.ChestAccessory,
    AvatarFigurePartType.Head,
    AvatarFigurePartType.Hair,
    AvatarFigurePartType.FaceAccessory,
    AvatarFigurePartType.EyeAccessory,
    AvatarFigurePartType.HeadAccessory,
    AvatarFigurePartType.HeadAccessoryExtra,
    AvatarFigurePartType.CoatChest,
    AvatarFigurePartType.ChestPrint,
];
