/**
 * `addons/VariablesWebApiAddon` (VARIABLES_WEB_API) - opens the room's variables to a web api:
 * a read key and a write key, each generated by the server on request
 * (`WiredGenerateWebApiKeyComposer`, answered by `WiredWebApiKeyResultMessage` - see
 * `handlers/wired/registerWiredWebApiKeyHandlers`), and the write key's bulk delete permission,
 * which needs a write key and a confirmation to turn on. The header's button opens the api docs.
 *
 * String param: `read key \t write key`. Int params: `[ bulk delete ]`, sent as 0 without a
 * write key.
 */
import type { WiredElementDefinition } from '../../WiredElement';
import { getWiredBoolean, getWiredString } from '../../WiredTriggerable';
import { AddonCodes } from './addonCodes';

export interface VariablesWebApiAddonForm {
    /** `§_-21R§.key`. */
    readKey: string;
    /** `§_-R22§.key`. */
    writeKey: string;
    /** `_permissions.get(0).selected` - `MASS_DELETION_CHECKBOX_ID`. */
    bulkDelete: boolean;
}

/** `onWiredApiKeyResultEvent` - a key the server generated for this box. */
export const applyWiredWebApiKey = (form: VariablesWebApiAddonForm, isReadKey: boolean, key: string): VariablesWebApiAddonForm =>
    (isReadKey ? { ...form, readKey: key } : { ...form, writeKey: key });

/** `onWriteKeyChange` - the bulk delete permission needs a write key. */
export const isWiredWebApiBulkDeleteDisabled = (form: VariablesWebApiAddonForm): boolean => (form.writeKey.length === 0);

export const variablesWebApiAddon: WiredElementDefinition<VariablesWebApiAddonForm> = {
    holder: 'addon',
    code: AddonCodes.VARIABLES_WEB_API,
    createForm: triggerable => ({
        readKey: getWiredString(triggerable, 0),
        writeKey: getWiredString(triggerable, 1),
        bulkDelete: getWiredBoolean(triggerable, 0),
    }),
    readStringParam: form => `${form.readKey}\t${form.writeKey}`,
    readIntParams: form => [ ((form.writeKey.length > 0) && form.bulkDelete) ? 1 : 0 ],
    headerButton: 'apiDocs',
    widthModifier: 1.4,
};
