/// Mirrors `AvatarFigurePartType` (packages/nitro-api/src/avatar/enum/AvatarFigurePartType.ts) -
/// the two-letter codes used both as figure-string segment keys and as `IFigurePart.type` values.
public enum AvatarFigurePartType: String, CaseIterable, Hashable, Sendable {
    case none = ""
    case body = "bd"
    case bodySwim = "bds"
    case chest = "ch"
    case chestAccessory = "ca"
    case chestPrint = "cp"
    case coatChest = "cc"
    case eyes = "ey"
    case eyeAccessory = "ea"
    case face = "fc"
    case faceAccessory = "fa"
    case hair = "hr"
    case hairBig = "hrb"
    case head = "hd"
    case headAccessory = "ha"
    case headAccessoryExtra = "he"
    case legs = "lg"
    case leftCoatSleeve = "lc"
    case leftHand = "lh"
    case leftHandItem = "li"
    case leftHandSwim = "lhs"
    case leftSleeve = "ls"
    case rightCoatSleeve = "rc"
    case rightHand = "rh"
    case rightHandItem = "ri"
    case rightHandSwim = "rhs"
    case rightSleeve = "rs"
    case shoes = "sh"
    case ss = "ss"
    case standard = "std"
    case waistAccessory = "wa"
}
