// Generated by scripts/generate-barrels.ts - run it instead of editing by hand.
export * from './registerInventoryBadgesHandlers';
export * from './registerInventoryBotsHandlers';
export * from './registerInventoryFurniHandlers';
export * from './registerInventoryMarketplaceHandlers';
export * from './registerInventoryPetsHandlers';
export * from './registerInventoryTradingHandlers';
