// Generated by scripts/generate-barrels.ts - run it instead of editing by hand.
export * from './registerInventoryBadgesHandlers';
export * from './registerInventoryFurniHandlers';
export * from './registerInventoryMarketplaceHandlers';
